// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: id_generator.proto

package server

import (
	"context"

	"github.com/wushiling50/aster/gen/id_generator"
	"github.com/wushiling50/aster/rpc/id_generator/internal/logic"
	"github.com/wushiling50/aster/rpc/id_generator/internal/svc"
)

type IdGeneratorServer struct {
	svcCtx *svc.ServiceContext
	id_generator.UnimplementedIdGeneratorServer
}

func NewIdGeneratorServer(svcCtx *svc.ServiceContext) *IdGeneratorServer {
	return &IdGeneratorServer{
		svcCtx: svcCtx,
	}
}

func (s *IdGeneratorServer) GetId(ctx context.Context, in *id_generator.GetIdReq) (*id_generator.GetIdResp, error) {
	l := logic.NewGetIdLogic(ctx, s.svcCtx)
	return l.GetId(in)
}
