// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: analysis.proto

package server

import (
	"context"

	"github.com/wushiling50/aster/gen/analysis"
	"github.com/wushiling50/aster/rpc/analysis/internal/logic"
	"github.com/wushiling50/aster/rpc/analysis/internal/svc"
)

type AnalysisServer struct {
	svcCtx *svc.ServiceContext
	analysis.UnimplementedAnalysisServer
}

func NewAnalysisServer(svcCtx *svc.ServiceContext) *AnalysisServer {
	return &AnalysisServer{
		svcCtx: svcCtx,
	}
}

func (s *AnalysisServer) UpdateLanguage(ctx context.Context, in *analysis.UpdateAnalysisReq) (*analysis.UpdateAnalysisResp, error) {
	l := logic.NewUpdateLanguageLogic(ctx, s.svcCtx)
	return l.UpdateLanguage(in)
}

func (s *AnalysisServer) UpdateNation(ctx context.Context, in *analysis.UpdateAnalysisReq) (*analysis.UpdateAnalysisResp, error) {
	l := logic.NewUpdateNationLogic(ctx, s.svcCtx)
	return l.UpdateNation(in)
}

func (s *AnalysisServer) UpdateScore(ctx context.Context, in *analysis.UpdateAnalysisReq) (*analysis.UpdateAnalysisResp, error) {
	l := logic.NewUpdateScoreLogic(ctx, s.svcCtx)
	return l.UpdateScore(in)
}

func (s *AnalysisServer) UpdateSummary(ctx context.Context, in *analysis.UpdateAnalysisReq) (*analysis.UpdateAnalysisResp, error) {
	l := logic.NewUpdateSummaryLogic(ctx, s.svcCtx)
	return l.UpdateSummary(in)
}

func (s *AnalysisServer) GetLanguages(ctx context.Context, in *analysis.GetAnalysisReq) (*analysis.GetLanguagesResp, error) {
	l := logic.NewGetLanguagesLogic(ctx, s.svcCtx)
	return l.GetLanguages(in)
}

func (s *AnalysisServer) GetNation(ctx context.Context, in *analysis.GetAnalysisReq) (*analysis.GetNationResp, error) {
	l := logic.NewGetNationLogic(ctx, s.svcCtx)
	return l.GetNation(in)
}

func (s *AnalysisServer) GetScore(ctx context.Context, in *analysis.GetAnalysisReq) (*analysis.GetScoreResp, error) {
	l := logic.NewGetScoreLogic(ctx, s.svcCtx)
	return l.GetScore(in)
}

func (s *AnalysisServer) GetSummary(ctx context.Context, in *analysis.GetAnalysisReq) (*analysis.GetSummaryResp, error) {
	l := logic.NewGetSummaryLogic(ctx, s.svcCtx)
	return l.GetSummary(in)
}
