// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: relation.proto

package relationclient

import (
	"context"

	"github.com/wushiling50/aster/gen/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCreateRepoReq                 = relation.AddCreateRepoReq
	AddCreateRepoResp                = relation.AddCreateRepoResp
	AddFollowReq                     = relation.AddFollowReq
	AddFollowResp                    = relation.AddFollowResp
	AddStarReq                       = relation.AddStarReq
	AddStarResp                      = relation.AddStarResp
	CreateRepo                       = relation.CreateRepo
	DelAllCreatedRepoReq             = relation.DelAllCreatedRepoReq
	DelAllCreatedRepoResp            = relation.DelAllCreatedRepoResp
	DelAllFollowerReq                = relation.DelAllFollowerReq
	DelAllFollowerResp               = relation.DelAllFollowerResp
	DelAllFollowingReq               = relation.DelAllFollowingReq
	DelAllFollowingResp              = relation.DelAllFollowingResp
	DelAllStaringDeveloperReq        = relation.DelAllStaringDeveloperReq
	DelAllStaringDeveloperResp       = relation.DelAllStaringDeveloperResp
	DelAllStarredRepoReq             = relation.DelAllStarredRepoReq
	DelAllStarredRepoResp            = relation.DelAllStarredRepoResp
	Follow                           = relation.Follow
	SearchCreatedRepoReq             = relation.SearchCreatedRepoReq
	SearchCreatedRepoResp            = relation.SearchCreatedRepoResp
	SearchFollowerByDeveloperIdReq   = relation.SearchFollowerByDeveloperIdReq
	SearchFollowerByDeveloperIdResp  = relation.SearchFollowerByDeveloperIdResp
	SearchFollowingByDeveloperIdReq  = relation.SearchFollowingByDeveloperIdReq
	SearchFollowingByDeveloperIdResp = relation.SearchFollowingByDeveloperIdResp
	SearchStaringDeveloperReq        = relation.SearchStaringDeveloperReq
	SearchStaringDeveloperResp       = relation.SearchStaringDeveloperResp
	SearchStarredRepoReq             = relation.SearchStarredRepoReq
	SearchStarredRepoResp            = relation.SearchStarredRepoResp
	Star                             = relation.Star

	Relation interface {
		// -----------------------CreateRepo-----------------------
		AddCreateRepo(ctx context.Context, in *AddCreateRepoReq, opts ...grpc.CallOption) (*AddCreateRepoResp, error)
		SearchCreatedRepo(ctx context.Context, in *SearchCreatedRepoReq, opts ...grpc.CallOption) (*SearchCreatedRepoResp, error)
		DelAllCreatedRepo(ctx context.Context, in *DelAllCreatedRepoReq, opts ...grpc.CallOption) (*DelAllCreatedRepoResp, error)
		// -----------------------Follow-----------------------
		AddFollow(ctx context.Context, in *AddFollowReq, opts ...grpc.CallOption) (*AddFollowResp, error)
		SearchFollowingByDeveloperId(ctx context.Context, in *SearchFollowingByDeveloperIdReq, opts ...grpc.CallOption) (*SearchFollowingByDeveloperIdResp, error)
		SearchFollowerByDeveloperId(ctx context.Context, in *SearchFollowerByDeveloperIdReq, opts ...grpc.CallOption) (*SearchFollowerByDeveloperIdResp, error)
		DelAllFollower(ctx context.Context, in *DelAllFollowerReq, opts ...grpc.CallOption) (*DelAllFollowerResp, error)
		DelAllFollowing(ctx context.Context, in *DelAllFollowingReq, opts ...grpc.CallOption) (*DelAllFollowingResp, error)
		// -----------------------Star-----------------------
		AddStar(ctx context.Context, in *AddStarReq, opts ...grpc.CallOption) (*AddStarResp, error)
		SearchStarredRepo(ctx context.Context, in *SearchStarredRepoReq, opts ...grpc.CallOption) (*SearchStarredRepoResp, error)
		SearchStaringDeveloper(ctx context.Context, in *SearchStaringDeveloperReq, opts ...grpc.CallOption) (*SearchStaringDeveloperResp, error)
		DelAllStarredRepo(ctx context.Context, in *DelAllStarredRepoReq, opts ...grpc.CallOption) (*DelAllStarredRepoResp, error)
		DelAllStaringDeveloper(ctx context.Context, in *DelAllStaringDeveloperReq, opts ...grpc.CallOption) (*DelAllStaringDeveloperResp, error)
	}

	defaultRelation struct {
		cli zrpc.Client
	}
)

func NewRelation(cli zrpc.Client) Relation {
	return &defaultRelation{
		cli: cli,
	}
}

// -----------------------CreateRepo-----------------------
func (m *defaultRelation) AddCreateRepo(ctx context.Context, in *AddCreateRepoReq, opts ...grpc.CallOption) (*AddCreateRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.AddCreateRepo(ctx, in, opts...)
}

func (m *defaultRelation) SearchCreatedRepo(ctx context.Context, in *SearchCreatedRepoReq, opts ...grpc.CallOption) (*SearchCreatedRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchCreatedRepo(ctx, in, opts...)
}

func (m *defaultRelation) DelAllCreatedRepo(ctx context.Context, in *DelAllCreatedRepoReq, opts ...grpc.CallOption) (*DelAllCreatedRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.DelAllCreatedRepo(ctx, in, opts...)
}

// -----------------------Follow-----------------------
func (m *defaultRelation) AddFollow(ctx context.Context, in *AddFollowReq, opts ...grpc.CallOption) (*AddFollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.AddFollow(ctx, in, opts...)
}

func (m *defaultRelation) SearchFollowingByDeveloperId(ctx context.Context, in *SearchFollowingByDeveloperIdReq, opts ...grpc.CallOption) (*SearchFollowingByDeveloperIdResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchFollowingByDeveloperId(ctx, in, opts...)
}

func (m *defaultRelation) SearchFollowerByDeveloperId(ctx context.Context, in *SearchFollowerByDeveloperIdReq, opts ...grpc.CallOption) (*SearchFollowerByDeveloperIdResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchFollowerByDeveloperId(ctx, in, opts...)
}

func (m *defaultRelation) DelAllFollower(ctx context.Context, in *DelAllFollowerReq, opts ...grpc.CallOption) (*DelAllFollowerResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.DelAllFollower(ctx, in, opts...)
}

func (m *defaultRelation) DelAllFollowing(ctx context.Context, in *DelAllFollowingReq, opts ...grpc.CallOption) (*DelAllFollowingResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.DelAllFollowing(ctx, in, opts...)
}

// -----------------------Star-----------------------
func (m *defaultRelation) AddStar(ctx context.Context, in *AddStarReq, opts ...grpc.CallOption) (*AddStarResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.AddStar(ctx, in, opts...)
}

func (m *defaultRelation) SearchStarredRepo(ctx context.Context, in *SearchStarredRepoReq, opts ...grpc.CallOption) (*SearchStarredRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchStarredRepo(ctx, in, opts...)
}

func (m *defaultRelation) SearchStaringDeveloper(ctx context.Context, in *SearchStaringDeveloperReq, opts ...grpc.CallOption) (*SearchStaringDeveloperResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchStaringDeveloper(ctx, in, opts...)
}

func (m *defaultRelation) DelAllStarredRepo(ctx context.Context, in *DelAllStarredRepoReq, opts ...grpc.CallOption) (*DelAllStarredRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.DelAllStarredRepo(ctx, in, opts...)
}

func (m *defaultRelation) DelAllStaringDeveloper(ctx context.Context, in *DelAllStaringDeveloperReq, opts ...grpc.CallOption) (*DelAllStaringDeveloperResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.DelAllStaringDeveloper(ctx, in, opts...)
}
