// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: relation.proto

package relationclient

import (
	"context"

	"github.com/wushiling50/aster/gen/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCreateRepoReq                 = relation.AddCreateRepoReq
	AddCreateRepoResp                = relation.AddCreateRepoResp
	AddFollowReq                     = relation.AddFollowReq
	AddFollowResp                    = relation.AddFollowResp
	AddForkReq                       = relation.AddForkReq
	AddForkResp                      = relation.AddForkResp
	AddStarReq                       = relation.AddStarReq
	AddStarResp                      = relation.AddStarResp
	CheckFollowResp                  = relation.CheckFollowResp
	CheckIfFollowReq                 = relation.CheckIfFollowReq
	CheckIfStarReq                   = relation.CheckIfStarReq
	CheckIfStarResp                  = relation.CheckIfStarResp
	CreateRepo                       = relation.CreateRepo
	Follow                           = relation.Follow
	Fork                             = relation.Fork
	GetOriginReq                     = relation.GetOriginReq
	GetOriginResp                    = relation.GetOriginResp
	SearchCreatedRepoReq             = relation.SearchCreatedRepoReq
	SearchCreatedRepoResp            = relation.SearchCreatedRepoResp
	SearchFollowerByDeveloperIdReq   = relation.SearchFollowerByDeveloperIdReq
	SearchFollowerByDeveloperIdResp  = relation.SearchFollowerByDeveloperIdResp
	SearchFollowingByDeveloperIdReq  = relation.SearchFollowingByDeveloperIdReq
	SearchFollowingByDeveloperIdResp = relation.SearchFollowingByDeveloperIdResp
	SearchForkReq                    = relation.SearchForkReq
	SearchForkResp                   = relation.SearchForkResp
	SearchStaringDeveloperReq        = relation.SearchStaringDeveloperReq
	SearchStaringDeveloperResp       = relation.SearchStaringDeveloperResp
	SearchStarredRepoReq             = relation.SearchStarredRepoReq
	SearchStarredRepoResp            = relation.SearchStarredRepoResp
	Star                             = relation.Star
	UpdateCreateRepoReq              = relation.UpdateCreateRepoReq
	UpdateCreateRepoResp             = relation.UpdateCreateRepoResp
	UpdateFollowerReq                = relation.UpdateFollowerReq
	UpdateFollowerResp               = relation.UpdateFollowerResp
	UpdateFollowingReq               = relation.UpdateFollowingReq
	UpdateFollowingResp              = relation.UpdateFollowingResp
	UpdateForkReq                    = relation.UpdateForkReq
	UpdateForkResp                   = relation.UpdateForkResp
	UpdateStarredRepoReq             = relation.UpdateStarredRepoReq
	UpdateStarredRepoResp            = relation.UpdateStarredRepoResp

	Relation interface {
		// -----------------------CreateRepo-----------------------
		AddCreateRepo(ctx context.Context, in *AddCreateRepoReq, opts ...grpc.CallOption) (*AddCreateRepoResp, error)
		SearchCreatedRepo(ctx context.Context, in *SearchCreatedRepoReq, opts ...grpc.CallOption) (*SearchCreatedRepoResp, error)
		UpdateCreateRepo(ctx context.Context, in *UpdateCreateRepoReq, opts ...grpc.CallOption) (*UpdateCreateRepoResp, error)
		// -----------------------Follow-----------------------
		AddFollow(ctx context.Context, in *AddFollowReq, opts ...grpc.CallOption) (*AddFollowResp, error)
		CheckIfFollow(ctx context.Context, in *CheckIfFollowReq, opts ...grpc.CallOption) (*CheckFollowResp, error)
		SearchFollowingByDeveloperId(ctx context.Context, in *SearchFollowingByDeveloperIdReq, opts ...grpc.CallOption) (*SearchFollowingByDeveloperIdResp, error)
		SearchFollowerByDeveloperId(ctx context.Context, in *SearchFollowerByDeveloperIdReq, opts ...grpc.CallOption) (*SearchFollowerByDeveloperIdResp, error)
		UpdateFollowing(ctx context.Context, in *UpdateFollowingReq, opts ...grpc.CallOption) (*UpdateFollowingResp, error)
		UpdateFollower(ctx context.Context, in *UpdateFollowerReq, opts ...grpc.CallOption) (*UpdateFollowerResp, error)
		// -----------------------Fork-----------------------
		AddFork(ctx context.Context, in *AddForkReq, opts ...grpc.CallOption) (*AddForkResp, error)
		GetOrigin(ctx context.Context, in *GetOriginReq, opts ...grpc.CallOption) (*GetOriginResp, error)
		SearchFork(ctx context.Context, in *SearchForkReq, opts ...grpc.CallOption) (*SearchForkResp, error)
		UpdateFork(ctx context.Context, in *UpdateForkReq, opts ...grpc.CallOption) (*UpdateForkResp, error)
		// -----------------------Star-----------------------
		AddStar(ctx context.Context, in *AddStarReq, opts ...grpc.CallOption) (*AddStarResp, error)
		CheckIfStar(ctx context.Context, in *CheckIfStarReq, opts ...grpc.CallOption) (*CheckIfStarResp, error)
		SearchStarredRepo(ctx context.Context, in *SearchStarredRepoReq, opts ...grpc.CallOption) (*SearchStarredRepoResp, error)
		SearchStaringDeveloper(ctx context.Context, in *SearchStaringDeveloperReq, opts ...grpc.CallOption) (*SearchStaringDeveloperResp, error)
		UpdateStarredRepo(ctx context.Context, in *UpdateStarredRepoReq, opts ...grpc.CallOption) (*UpdateStarredRepoResp, error)
	}

	defaultRelation struct {
		cli zrpc.Client
	}
)

func NewRelation(cli zrpc.Client) Relation {
	return &defaultRelation{
		cli: cli,
	}
}

// -----------------------CreateRepo-----------------------
func (m *defaultRelation) AddCreateRepo(ctx context.Context, in *AddCreateRepoReq, opts ...grpc.CallOption) (*AddCreateRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.AddCreateRepo(ctx, in, opts...)
}

func (m *defaultRelation) SearchCreatedRepo(ctx context.Context, in *SearchCreatedRepoReq, opts ...grpc.CallOption) (*SearchCreatedRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchCreatedRepo(ctx, in, opts...)
}

func (m *defaultRelation) UpdateCreateRepo(ctx context.Context, in *UpdateCreateRepoReq, opts ...grpc.CallOption) (*UpdateCreateRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.UpdateCreateRepo(ctx, in, opts...)
}

// -----------------------Follow-----------------------
func (m *defaultRelation) AddFollow(ctx context.Context, in *AddFollowReq, opts ...grpc.CallOption) (*AddFollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.AddFollow(ctx, in, opts...)
}

func (m *defaultRelation) CheckIfFollow(ctx context.Context, in *CheckIfFollowReq, opts ...grpc.CallOption) (*CheckFollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.CheckIfFollow(ctx, in, opts...)
}

func (m *defaultRelation) SearchFollowingByDeveloperId(ctx context.Context, in *SearchFollowingByDeveloperIdReq, opts ...grpc.CallOption) (*SearchFollowingByDeveloperIdResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchFollowingByDeveloperId(ctx, in, opts...)
}

func (m *defaultRelation) SearchFollowerByDeveloperId(ctx context.Context, in *SearchFollowerByDeveloperIdReq, opts ...grpc.CallOption) (*SearchFollowerByDeveloperIdResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchFollowerByDeveloperId(ctx, in, opts...)
}

func (m *defaultRelation) UpdateFollowing(ctx context.Context, in *UpdateFollowingReq, opts ...grpc.CallOption) (*UpdateFollowingResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.UpdateFollowing(ctx, in, opts...)
}

func (m *defaultRelation) UpdateFollower(ctx context.Context, in *UpdateFollowerReq, opts ...grpc.CallOption) (*UpdateFollowerResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.UpdateFollower(ctx, in, opts...)
}

// -----------------------Fork-----------------------
func (m *defaultRelation) AddFork(ctx context.Context, in *AddForkReq, opts ...grpc.CallOption) (*AddForkResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.AddFork(ctx, in, opts...)
}

func (m *defaultRelation) GetOrigin(ctx context.Context, in *GetOriginReq, opts ...grpc.CallOption) (*GetOriginResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.GetOrigin(ctx, in, opts...)
}

func (m *defaultRelation) SearchFork(ctx context.Context, in *SearchForkReq, opts ...grpc.CallOption) (*SearchForkResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchFork(ctx, in, opts...)
}

func (m *defaultRelation) UpdateFork(ctx context.Context, in *UpdateForkReq, opts ...grpc.CallOption) (*UpdateForkResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.UpdateFork(ctx, in, opts...)
}

// -----------------------Star-----------------------
func (m *defaultRelation) AddStar(ctx context.Context, in *AddStarReq, opts ...grpc.CallOption) (*AddStarResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.AddStar(ctx, in, opts...)
}

func (m *defaultRelation) CheckIfStar(ctx context.Context, in *CheckIfStarReq, opts ...grpc.CallOption) (*CheckIfStarResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.CheckIfStar(ctx, in, opts...)
}

func (m *defaultRelation) SearchStarredRepo(ctx context.Context, in *SearchStarredRepoReq, opts ...grpc.CallOption) (*SearchStarredRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchStarredRepo(ctx, in, opts...)
}

func (m *defaultRelation) SearchStaringDeveloper(ctx context.Context, in *SearchStaringDeveloperReq, opts ...grpc.CallOption) (*SearchStaringDeveloperResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.SearchStaringDeveloper(ctx, in, opts...)
}

func (m *defaultRelation) UpdateStarredRepo(ctx context.Context, in *UpdateStarredRepoReq, opts ...grpc.CallOption) (*UpdateStarredRepoResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.UpdateStarredRepo(ctx, in, opts...)
}
