// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type Developer struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Login     string `json:"login"`
	AvatarUrl string `json:"avatar_url"`
	Company   string `json:"company"`
	Location  string `json:"location"`
	Bio       string `json:"bio"`
	Blog      string `json:"blog"`
	Email     string `json:"email"`
	Followers int64  `json:"followers"`
	Following int64  `json:"following"`
	Stars     int64  `json:"stars"`
	Repos     int64  `json:"repos"`
	Gists     int64  `json:"gists"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type DeveloperWithScore struct {
	Developer Developer `json:"developer"`
	Score     Score     `json:"score"`
}

type GetDeveloperReq struct {
	Login string `path:"login"`
}

type GetDeveloperResp struct {
	BaseResp  BaseResp  `json:"base"`
	Developer Developer `json:"developer"`
}

type GetLanguageUsageReq struct {
	Login  string `path:"login"`
	TaskId string `form:"task_id"`
}

type GetLanguageUsageResp struct {
	BaseResp      BaseResp      `json:"base"`
	LanguageUsage LanguageUsage `json:"language_usage"`
}

type GetLanguagesReq struct {
}

type GetLanguagesResp struct {
	BaseResp     BaseResp   `json:"base"`
	LanguageList []Language `json:"language_list"`
}

type GetNationReq struct {
	Login  string `path:"login"`
	TaskId string `form:"task_id"`
}

type GetNationResp struct {
	BaseResp BaseResp `json:"base"`
	Nation   Nation   `json:"nation"`
}

type GetScoreRankReq struct {
	Language string `form:"language,optional"`
	Nation   string `form:"nation,optional"`
	Limit    int64  `form:"limit,optional,default=50"`
	Offset   int64  `form:"offset,optional,default=0"`
}

type GetScoreRankResp struct {
	BaseResp BaseResp              `json:"base"`
	Rank     []*DeveloperWithScore `json:"rank"`
	Total    int64                 `json:"total"`
}

type GetScoreReq struct {
	Login  string `path:"login"`
	TaskId string `form:"task_id"`
}

type GetScoreResp struct {
	BaseResp BaseResp `json:"base"`
	Score    Score    `json:"score"`
}

type GetSummaryReq struct {
	Login  string `path:"login"`
	TaskId string `form:"task_id"`
}

type GetSummaryResp struct {
	BaseResp BaseResp `json:"base"`
	Summary  Summary  `json:"summary"`
}

type Language struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

type LanguageUsage struct {
	Id        int64                    `json:"id"`
	Languages []LanguageWithPercentage `json:"languages"`
	UpdatedAt string                   `json:"updated_at"`
}

type LanguageWithPercentage struct {
	Language   Language `json:"language"`
	Percentage float64  `json:"percentage"`
}

type Nation struct {
	Id         int64   `json:"id"`
	Nation     string  `json:"nation"`
	Confidence float64 `json:"confidence"`
}

type PostTaskReq struct {
	Login string `path:"login"`
}

type PostTaskResp struct {
	BaseResp BaseResp `json:"base"`
	TaskId   TaskId   `json:"task_id"`
}

type Score struct {
	Id        int64   `json:"id"`
	Score     float64 `json:"score"`
	UpdatedAt string  `json:"updated_at"`
}

type Summary struct {
	Id        int64  `json:"id"`
	Summary   string `json:"summary"`
	UpdatedAt string `json:"updated_at"`
}

type TaskId struct {
	TaskId string `json:"task_id"`
}

type TaskState struct {
	State  string `json:"state"`
	Reason string `json:"reason"`
}
