import re

from github import Github

REGIONAL_EMAIL_PROVIDERS = {
    "AL": ["albtelecom.al", "aon.al", "abcom.al"],
    "AR": ["fibertel.com.ar", "speedy.com.ar"],
    "AT": ["aon.at", "chello.at", "drei.at"],
    "AU": ["bigpond.com", "bigpond.net.au", "iinet.net.au", "optusnet.com.au", "telstra.com"],
    "BE": ["skynet.be", "proximus.be", "telenet.be"],
    "BG": ["abv.bg", "dir.bg", "mail.bg"],
    "BR": ["bol.com.br", "globo.com", "terra.com.br", "uol.com.br"],
    "CA": ["sasktel.net", "shaw.ca", "telus.net", "videotron.ca", "rogers.com"],
    "CH": ["bluewin.ch", "hispeed.ch", "sunrise.ch", "bluemail.ch"],
    "CL": ["vtr.net", "movistar.cl", "entel.cl"],
    "CN": ["126.com", "163.com", "qq.com", "sina.com", "sohu.com"],
    "CO": ["etb.net.co", "une.net.co"],
    "CZ": ["seznam.cz", "centrum.cz", "email.cz"],
    "DE": ["t-online.de", "web.de", "gmx.de", "freenet.de"],
    "DK": ["jubii.dk", "mail.dk", "ofir.dk"],
    "EE": ["hot.ee", "mail.ee"],
    "ES": ["telefonica.net", "terra.es", "ono.com", "jazztel.com"],
    "FI": ["kolumbus.fi", "jippii.fi", "saunalahti.fi"],
    "FR": ["orange.fr", "sfr.fr", "wanadoo.fr", "laposte.net", "free.fr"],
    "GR": ["hol.gr", "otenet.gr", "forthnet.gr"],
    "HK": ["netvigator.com", "hkbn.net"],
    "HU": ["chello.hu", "digikabel.hu", "freemail.hu", "citromail.hu"],
    "IE": ["eircom.net", "eir.ie"],
    "IL": ["walla.co.il", "netvision.net.il", "bezeqint.net"],
    "IN": ["rediffmail.com", "in.com", "vsnl.com", "airtelmail.in"],
    "IS": ["simnet.is", "visir.is"],
    "IT": ["alice.it", "tin.it", "libero.it"],
    "JP": ["nifty.com", "ocn.ne.jp", "i.softbank.jp", "docomo.ne.jp"],
    "KR": ["naver.com", "daum.net", "nate.com", "hanmail.net"],
    "LT": ["takas.lt", "mic.lt"],
    "LV": ["inbox.lv", "apollo.lv"],
    "MX": ["prodigy.net.mx", "axtel.net", "totalplay.com.mx"],
    "NL": ["chello.nl", "hetnet.nl", "kpnmail.nl", "xs4all.nl", "zeelandnet.nl"],
    "NO": ["online.no", "start.no"],
    "NZ": ["xtra.co.nz", "clear.net.nz", "spark.co.nz"],
    "PH": ["pldtdsl.net"],
    "PL": ["wp.pl", "onet.pl", "o2.pl", "interia.pl"],
    "PT": ["clix.pt", "mail.telepac.pt", "sapo.pt", "nos.pt"],
    "RO": ["rdslink.ro", "clicknet.ro"],
    "RS": ["sbb.rs", "eunet.rs"],
    "RU": ["mail.ru", "yandex.ru", "rambler.ru"],
    "SE": ["telia.com", "bredband.net", "passagen.se"],
    "SG": ["singnet.com.sg", "pacific.net.sg", "myrepublic.com.sg", "starhub.net"],
    "SI": ["siol.net", "volja.net"],
    "SK": ["azet.sk", "post.sk", "zoznam.sk"],
    "TH": ["truemail.co.th", "in.th"],
    "TR": ["superonline.com", "ttnet.net.tr", "turk.net"],
    "TW": ["pchome.com.tw", "ms13.hinet.net"],
    "UA": ["i.ua", "meta.ua", "ukr.net"],
    "UK": ["btinternet.com", "ntlworld.com", "talktalk.net", "sky.com", "virginmedia.com"],
    "US": ["aol.com", "comcast.net", "verizon.net", "att.net", "spectrum.net"],
    "VN": ["vnn.vn", "hcm.vnn.vn", "hn.vnn.vn"],
    "ZA": ["webmail.co.za", "telkomsa.net"],
}

REGIONAL_CCTLD = {
    ".ad": "ad",
    ".ae": "ae",
    ".af": "af",
    ".ag": "ag",
    ".ai": "ai",
    ".al": "al",
    ".am": "am",
    ".ao": "ao",
    ".aq": "aq",
    ".ar": "ar",
    ".as": "as",
    ".at": "at",
    ".au": "au",
    ".aw": "aw",
    ".ax": "ax",
    ".az": "az",
    ".ba": "ba",
    ".bb": "bb",
    ".bd": "bd",
    ".be": "be",
    ".bf": "bf",
    ".bg": "bg",
    ".bh": "bh",
    ".bi": "bi",
    ".bj": "bj",
    ".gp": "mf",
    ".bm": "bm",
    ".bn": "bn",
    ".bo": "bo",
    ".bq": "bq",
    ".br": "br",
    ".bs": "bs",
    ".bt": "bt",
    ".bv": "bv",
    ".bw": "bw",
    ".by": "by",
    ".bz": "bz",
    ".ca": "ca",
    ".cc": "cc",
    ".cd": "cd",
    ".cf": "cf",
    ".cg": "cg",
    ".ch": "ch",
    ".ci": "ci",
    ".ck": "ck",
    ".cl": "cl",
    ".cm": "cm",
    ".cn": "cn",
    ".co": "co",
    ".cr": "cr",
    ".cu": "cu",
    ".cv": "cv",
    ".cw": "cw",
    ".cx": "cx",
    ".cy": "cy",
    ".cz": "cz",
    ".de": "de",
    ".dj": "dj",
    ".dk": "dk",
    ".dm": "dm",
    ".do": "do",
    ".dz": "dz",
    ".ec": "ec",
    ".ee": "ee",
    ".eg": "eg",
    ".eh": "eh",
    ".er": "er",
    ".es": "es",
    ".et": "et",
    ".fi": "fi",
    ".fj": "fj",
    ".fk": "fk",
    ".fm": "fm",
    ".fo": "fo",
    ".fr": "fr",
    ".ga": "ga",
    ".uk": "gb",
    ".gd": "gd",
    ".ge": "ge",
    ".gf": "gf",
    ".gg": "gg",
    ".gh": "gh",
    ".gi": "gi",
    ".gl": "gl",
    ".gm": "gm",
    ".gn": "gn",
    ".gq": "gq",
    ".gr": "gr",
    ".gs": "gs",
    ".gt": "gt",
    ".gu": "gu",
    ".gw": "gw",
    ".gy": "gy",
    ".hk": "hk",
    ".hm": "hm",
    ".hn": "hn",
    ".hr": "hr",
    ".ht": "ht",
    ".hu": "hu",
    ".id": "id",
    ".ie": "ie",
    ".il": "il",
    ".im": "im",
    ".in": "in",
    ".io": "io",
    ".iq": "iq",
    ".ir": "ir",
    ".is": "is",
    ".it": "it",
    ".je": "je",
    ".jm": "jm",
    ".jo": "jo",
    ".jp": "jp",
    ".ke": "ke",
    ".kg": "kg",
    ".kh": "kh",
    ".ki": "ki",
    ".km": "km",
    ".kn": "kn",
    ".kp": "kp",
    ".kr": "kr",
    ".kw": "kw",
    ".ky": "ky",
    ".kz": "kz",
    ".la": "la",
    ".lb": "lb",
    ".lc": "lc",
    ".li": "li",
    ".lk": "lk",
    ".lr": "lr",
    ".ls": "ls",
    ".lt": "lt",
    ".lu": "lu",
    ".lv": "lv",
    ".ly": "ly",
    ".ma": "ma",
    ".mc": "mc",
    ".md": "md",
    ".me": "me",
    ".mg": "mg",
    ".mh": "mh",
    ".mk": "mk",
    ".ml": "ml",
    ".mm": "mm",
    ".mn": "mn",
    ".mo": "mo",
    ".mp": "mp",
    ".mq": "mq",
    ".mr": "mr",
    ".ms": "ms",
    ".mt": "mt",
    ".mu": "mu",
    ".mv": "mv",
    ".mw": "mw",
    ".mx": "mx",
    ".my": "my",
    ".mz": "mz",
    ".na": "na",
    ".nc": "nc",
    ".ne": "ne",
    ".nf": "nf",
    ".ng": "ng",
    ".ni": "ni",
    ".nl": "nl",
    ".no": "no",
    ".np": "np",
    ".nr": "nr",
    ".nu": "nu",
    ".nz": "nz",
    ".om": "om",
    ".pa": "pa",
    ".pe": "pe",
    ".pf": "pf",
    ".pg": "pg",
    ".ph": "ph",
    ".pk": "pk",
    ".pl": "pl",
    ".pm": "pm",
    ".pn": "pn",
    ".pr": "pr",
    ".ps": "ps",
    ".pt": "pt",
    ".pw": "pw",
    ".py": "py",
    ".qa": "qa",
    ".re": "re",
    ".ro": "ro",
    ".rs": "rs",
    ".ru": "ru",
    ".rw": "rw",
    ".sa": "sa",
    ".sb": "sb",
    ".sc": "sc",
    ".sd": "sd",
    ".ss": "ss",
    ".se": "se",
    ".sg": "sg",
    ".sh": "sh",
    ".si": "si",
    ".sj": "sj",
    ".sk": "sk",
    ".sl": "sl",
    ".sm": "sm",
    ".sn": "sn",
    ".so": "so",
    ".sr": "sr",
    ".st": "st",
    ".sv": "sv",
    ".sx": "sx",
    ".sy": "sy",
    ".sz": "sz",
    ".tc": "tc",
    ".td": "td",
    ".tf": "tf",
    ".tg": "tg",
    ".th": "th",
    ".tj": "tj",
    ".tk": "tk",
    ".tl": "tl",
    ".tm": "tm",
    ".tn": "tn",
    ".to": "to",
    ".tr": "tr",
    ".tt": "tt",
    ".tv": "tv",
    ".tw": "tw",
    ".tz": "tz",
    ".ua": "ua",
    ".ug": "ug",
    ".um": "um",
    ".us": "us",
    ".uy": "uy",
    ".uz": "uz",
    ".va": "va",
    ".vc": "vc",
    ".ve": "ve",
    ".vg": "vg",
    ".vi": "vi",
    ".vn": "vn",
    ".vu": "vu",
    ".wf": "wf",
    ".ws": "ws",
    ".ye": "ye",
    ".yt": "yt",
    ".za": "za",
    ".zm": "zm",
    ".zw": "zw",
    ".cs": "cs",
    ".an": "an"
}


def guess_by_profile_email(handle: str, gh: Github):
    # 获取用户邮箱
    email = gh.get_user(handle).email
    if email is None:
        return None

    # 使用正则提取域名
    m = re.match(r'.*@(.*)', email)
    if m is None:
        return None
    domain = m.group(1)

    # 在邮箱提供商字典中查找
    for country, providers in REGIONAL_EMAIL_PROVIDERS.items():
        for provider in providers:
            if domain.endswith(provider):
                return country.lower()
    
    # 在顶级域名字典中查找
    for cctld, country in REGIONAL_CCTLD.items():
        if domain.endswith(cctld):
            return country

    return None
