// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package contribution

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentOfUserUpdatedAtFieldNames          = builder.RawFieldNames(&CommentOfUserUpdatedAt{})
	commentOfUserUpdatedAtRows                = strings.Join(commentOfUserUpdatedAtFieldNames, ",")
	commentOfUserUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(commentOfUserUpdatedAtFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentOfUserUpdatedAtRowsWithPlaceHolder = strings.Join(stringx.Remove(commentOfUserUpdatedAtFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCommentOfUserUpdatedAtDataIdPrefix = "cache:commentOfUserUpdatedAt:dataId:"
)

type (
	commentOfUserUpdatedAtModel interface {
		Insert(ctx context.Context, data *CommentOfUserUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*CommentOfUserUpdatedAt, error)
		Update(ctx context.Context, data *CommentOfUserUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultCommentOfUserUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	CommentOfUserUpdatedAt struct {
		DataId        int64     `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId   int64     `db:"developer_id"` // Unique GitHub User ID
		DataCreatedAt time.Time `db:"data_created_at"`
		DataUpdatedAt time.Time `db:"data_updated_at"` // update data time
	}
)

func newCommentOfUserUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentOfUserUpdatedAtModel {
	return &defaultCommentOfUserUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`comment_of_user_updated_at`",
	}
}

func (m *defaultCommentOfUserUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	commentOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheCommentOfUserUpdatedAtDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, commentOfUserUpdatedAtDataIdKey)
	return err
}

func (m *defaultCommentOfUserUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*CommentOfUserUpdatedAt, error) {
	commentOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheCommentOfUserUpdatedAtDataIdPrefix, dataId)
	var resp CommentOfUserUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, commentOfUserUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", commentOfUserUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentOfUserUpdatedAtModel) Insert(ctx context.Context, data *CommentOfUserUpdatedAt) (sql.Result, error) {
	commentOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheCommentOfUserUpdatedAtDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, commentOfUserUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt)
	}, commentOfUserUpdatedAtDataIdKey)
	return ret, err
}

func (m *defaultCommentOfUserUpdatedAtModel) Update(ctx context.Context, data *CommentOfUserUpdatedAt) error {
	commentOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheCommentOfUserUpdatedAtDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, commentOfUserUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt, data.DataId)
	}, commentOfUserUpdatedAtDataIdKey)
	return err
}

func (m *defaultCommentOfUserUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCommentOfUserUpdatedAtDataIdPrefix, primary)
}

func (m *defaultCommentOfUserUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", commentOfUserUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentOfUserUpdatedAtModel) tableName() string {
	return m.table
}
