// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package contribution

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	contributionFieldNames          = builder.RawFieldNames(&Contribution{})
	contributionRows                = strings.Join(contributionFieldNames, ",")
	contributionRowsExpectAutoSet   = strings.Join(stringx.Remove(contributionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	contributionRowsWithPlaceHolder = strings.Join(stringx.Remove(contributionFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheContributionDataIdPrefix = "cache:contribution:dataId:"
)

type (
	contributionModel interface {
		Insert(ctx context.Context, data *Contribution) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*Contribution, error)
		Update(ctx context.Context, data *Contribution) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultContributionModel struct {
		sqlc.CachedConn
		table string
	}

	Contribution struct {
		DataId         int64        `db:"data_id"`         // Generated Primary Key, Must Not Be Changed
		ContributionId int64        `db:"contribution_id"` // Unique Contribution ID
		DeveloperId    int64        `db:"developer_id"`    // Unique GitHub User ID
		RepoId         int64        `db:"repo_id"`         // Unique GitHub Repository ID
		Category       string       `db:"category"`        // Category
		Content        string       `db:"content"`         // Contribution Content
		CreatedAt      time.Time    `db:"created_at"`      // Original creation timestamp
		UpdatedAt      time.Time    `db:"updated_at"`      // Last update timestamp
		DataCreatedAt  time.Time    `db:"data_created_at"`
		DataUpdatedAt  time.Time    `db:"data_updated_at"` // update data time
		DataDeletedAt  sql.NullTime `db:"data_deleted_at"`
	}
)

func newContributionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultContributionModel {
	return &defaultContributionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`contribution`",
	}
}

func (m *defaultContributionModel) Delete(ctx context.Context, dataId int64) error {
	contributionDataIdKey := fmt.Sprintf("%s%v", cacheContributionDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, contributionDataIdKey)
	return err
}

func (m *defaultContributionModel) FindOne(ctx context.Context, dataId int64) (*Contribution, error) {
	contributionDataIdKey := fmt.Sprintf("%s%v", cacheContributionDataIdPrefix, dataId)
	var resp Contribution
	err := m.QueryRowCtx(ctx, &resp, contributionDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", contributionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContributionModel) Insert(ctx context.Context, data *Contribution) (sql.Result, error) {
	contributionDataIdKey := fmt.Sprintf("%s%v", cacheContributionDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, contributionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.ContributionId, data.DeveloperId, data.RepoId, data.Category, data.Content, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt)
	}, contributionDataIdKey)
	return ret, err
}

func (m *defaultContributionModel) Update(ctx context.Context, data *Contribution) error {
	contributionDataIdKey := fmt.Sprintf("%s%v", cacheContributionDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, contributionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ContributionId, data.DeveloperId, data.RepoId, data.Category, data.Content, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt, data.DataId)
	}, contributionDataIdKey)
	return err
}

func (m *defaultContributionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheContributionDataIdPrefix, primary)
}

func (m *defaultContributionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", contributionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultContributionModel) tableName() string {
	return m.table
}
