// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package contribution

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reviewOfUserUpdatedAtFieldNames          = builder.RawFieldNames(&ReviewOfUserUpdatedAt{})
	reviewOfUserUpdatedAtRows                = strings.Join(reviewOfUserUpdatedAtFieldNames, ",")
	reviewOfUserUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(reviewOfUserUpdatedAtFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	reviewOfUserUpdatedAtRowsWithPlaceHolder = strings.Join(stringx.Remove(reviewOfUserUpdatedAtFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheReviewOfUserUpdatedAtDataIdPrefix = "cache:reviewOfUserUpdatedAt:dataId:"
)

type (
	reviewOfUserUpdatedAtModel interface {
		Insert(ctx context.Context, data *ReviewOfUserUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*ReviewOfUserUpdatedAt, error)
		Update(ctx context.Context, data *ReviewOfUserUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultReviewOfUserUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	ReviewOfUserUpdatedAt struct {
		DataId        int64     `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId   int64     `db:"developer_id"` // Unique GitHub User ID
		DataCreatedAt time.Time `db:"data_created_at"`
		DataUpdatedAt time.Time `db:"data_updated_at"` // update data time
	}
)

func newReviewOfUserUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultReviewOfUserUpdatedAtModel {
	return &defaultReviewOfUserUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`review_of_user_updated_at`",
	}
}

func (m *defaultReviewOfUserUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	reviewOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheReviewOfUserUpdatedAtDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, reviewOfUserUpdatedAtDataIdKey)
	return err
}

func (m *defaultReviewOfUserUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*ReviewOfUserUpdatedAt, error) {
	reviewOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheReviewOfUserUpdatedAtDataIdPrefix, dataId)
	var resp ReviewOfUserUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, reviewOfUserUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", reviewOfUserUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReviewOfUserUpdatedAtModel) Insert(ctx context.Context, data *ReviewOfUserUpdatedAt) (sql.Result, error) {
	reviewOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheReviewOfUserUpdatedAtDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, reviewOfUserUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt)
	}, reviewOfUserUpdatedAtDataIdKey)
	return ret, err
}

func (m *defaultReviewOfUserUpdatedAtModel) Update(ctx context.Context, data *ReviewOfUserUpdatedAt) error {
	reviewOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheReviewOfUserUpdatedAtDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, reviewOfUserUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt, data.DataId)
	}, reviewOfUserUpdatedAtDataIdKey)
	return err
}

func (m *defaultReviewOfUserUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheReviewOfUserUpdatedAtDataIdPrefix, primary)
}

func (m *defaultReviewOfUserUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", reviewOfUserUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultReviewOfUserUpdatedAtModel) tableName() string {
	return m.table
}
