// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package analysis

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	languagesFieldNames          = builder.RawFieldNames(&Languages{})
	languagesRows                = strings.Join(languagesFieldNames, ",")
	languagesRowsExpectAutoSet   = strings.Join(stringx.Remove(languagesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	languagesRowsWithPlaceHolder = strings.Join(stringx.Remove(languagesFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLanguagesDataIdPrefix = "cache:languages:dataId:"
)

type (
	languagesModel interface {
		Insert(ctx context.Context, data *Languages) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*Languages, error)
		Update(ctx context.Context, data *Languages) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultLanguagesModel struct {
		sqlc.CachedConn
		table string
	}

	Languages struct {
		DataId        int64        `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId   int64        `db:"developer_id"` // Unique GitHub User ID
		Language      string       `db:"language"`     // Programming Languages Used (JSON Format)
		DataCreatedAt time.Time    `db:"data_created_at"`
		DataUpdatedAt time.Time    `db:"data_updated_at"` // update data time
		DataDeletedAt sql.NullTime `db:"data_deleted_at"`
	}
)

func newLanguagesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLanguagesModel {
	return &defaultLanguagesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`languages`",
	}
}

func (m *defaultLanguagesModel) Delete(ctx context.Context, dataId int64) error {
	languagesDataIdKey := fmt.Sprintf("%s%v", cacheLanguagesDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, languagesDataIdKey)
	return err
}

func (m *defaultLanguagesModel) FindOne(ctx context.Context, dataId int64) (*Languages, error) {
	languagesDataIdKey := fmt.Sprintf("%s%v", cacheLanguagesDataIdPrefix, dataId)
	var resp Languages
	err := m.QueryRowCtx(ctx, &resp, languagesDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", languagesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLanguagesModel) Insert(ctx context.Context, data *Languages) (sql.Result, error) {
	languagesDataIdKey := fmt.Sprintf("%s%v", cacheLanguagesDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, languagesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.Language, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt)
	}, languagesDataIdKey)
	return ret, err
}

func (m *defaultLanguagesModel) Update(ctx context.Context, data *Languages) error {
	languagesDataIdKey := fmt.Sprintf("%s%v", cacheLanguagesDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, languagesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeveloperId, data.Language, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt, data.DataId)
	}, languagesDataIdKey)
	return err
}

func (m *defaultLanguagesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLanguagesDataIdPrefix, primary)
}

func (m *defaultLanguagesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", languagesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLanguagesModel) tableName() string {
	return m.table
}
