// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package analysis

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	nationFieldNames          = builder.RawFieldNames(&Nation{})
	nationRows                = strings.Join(nationFieldNames, ",")
	nationRowsExpectAutoSet   = strings.Join(stringx.Remove(nationFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	nationRowsWithPlaceHolder = strings.Join(stringx.Remove(nationFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheNationDataIdPrefix      = "cache:nation:dataId:"
	cacheNationDeveloperIdPrefix = "cache:nation:developerId:"
)

type (
	nationModel interface {
		Insert(ctx context.Context, data *Nation) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*Nation, error)
		FindOneByDeveloperId(ctx context.Context, developerId int64) (*Nation, error)
		Update(ctx context.Context, data *Nation) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultNationModel struct {
		sqlc.CachedConn
		table string
	}

	Nation struct {
		DataId      int64        `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId int64        `db:"developer_id"` // Unique GitHub User ID
		Nation      string       `db:"nation"`       // Nation
		Confidence  float64      `db:"confidence"`   // Confidence
		CreatedAt   time.Time    `db:"created_at"`
		UpdatedAt   time.Time    `db:"updated_at"` // update data time
		DeletedAt   sql.NullTime `db:"deleted_at"`
	}
)

func newNationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNationModel {
	return &defaultNationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`nation`",
	}
}

func (m *defaultNationModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	nationDataIdKey := fmt.Sprintf("%s%v", cacheNationDataIdPrefix, dataId)
	nationDeveloperIdKey := fmt.Sprintf("%s%v", cacheNationDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, nationDataIdKey, nationDeveloperIdKey)
	return err
}

func (m *defaultNationModel) FindOne(ctx context.Context, dataId int64) (*Nation, error) {
	nationDataIdKey := fmt.Sprintf("%s%v", cacheNationDataIdPrefix, dataId)
	var resp Nation
	err := m.QueryRowCtx(ctx, &resp, nationDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", nationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNationModel) FindOneByDeveloperId(ctx context.Context, developerId int64) (*Nation, error) {
	nationDeveloperIdKey := fmt.Sprintf("%s%v", cacheNationDeveloperIdPrefix, developerId)
	var resp Nation
	err := m.QueryRowIndexCtx(ctx, &resp, nationDeveloperIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `developer_id` = ? limit 1", nationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, developerId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNationModel) Insert(ctx context.Context, data *Nation) (sql.Result, error) {
	nationDataIdKey := fmt.Sprintf("%s%v", cacheNationDataIdPrefix, data.DataId)
	nationDeveloperIdKey := fmt.Sprintf("%s%v", cacheNationDeveloperIdPrefix, data.DeveloperId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, nationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.Nation, data.Confidence, data.DeletedAt)
	}, nationDataIdKey, nationDeveloperIdKey)
	return ret, err
}

func (m *defaultNationModel) Update(ctx context.Context, newData *Nation) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	nationDataIdKey := fmt.Sprintf("%s%v", cacheNationDataIdPrefix, data.DataId)
	nationDeveloperIdKey := fmt.Sprintf("%s%v", cacheNationDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, nationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeveloperId, newData.Nation, newData.Confidence, newData.DeletedAt, newData.DataId)
	}, nationDataIdKey, nationDeveloperIdKey)
	return err
}

func (m *defaultNationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheNationDataIdPrefix, primary)
}

func (m *defaultNationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", nationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNationModel) tableName() string {
	return m.table
}
