// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package analysis

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	scoreFieldNames          = builder.RawFieldNames(&Score{})
	scoreRows                = strings.Join(scoreFieldNames, ",")
	scoreRowsExpectAutoSet   = strings.Join(stringx.Remove(scoreFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	scoreRowsWithPlaceHolder = strings.Join(stringx.Remove(scoreFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheScoreDataIdPrefix = "cache:score:dataId:"
)

type (
	scoreModel interface {
		Insert(ctx context.Context, data *Score) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*Score, error)
		Update(ctx context.Context, data *Score) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultScoreModel struct {
		sqlc.CachedConn
		table string
	}

	Score struct {
		DataId         int64        `db:"data_id"`         // Generated Primary Key, Must Not Be Changed
		ContributionId int64        `db:"contribution_id"` // Unique Contribution ID
		DeveloperId    int64        `db:"developer_id"`    // Unique GitHub User ID
		Score          float64      `db:"score"`           // score
		DataCreatedAt  time.Time    `db:"data_created_at"`
		DataUpdatedAt  time.Time    `db:"data_updated_at"` // update data time
		DataDeletedAt  sql.NullTime `db:"data_deleted_at"`
	}
)

func newScoreModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultScoreModel {
	return &defaultScoreModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`score`",
	}
}

func (m *defaultScoreModel) Delete(ctx context.Context, dataId int64) error {
	scoreDataIdKey := fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, scoreDataIdKey)
	return err
}

func (m *defaultScoreModel) FindOne(ctx context.Context, dataId int64) (*Score, error) {
	scoreDataIdKey := fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, dataId)
	var resp Score
	err := m.QueryRowCtx(ctx, &resp, scoreDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", scoreRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScoreModel) Insert(ctx context.Context, data *Score) (sql.Result, error) {
	scoreDataIdKey := fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, scoreRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.ContributionId, data.DeveloperId, data.Score, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt)
	}, scoreDataIdKey)
	return ret, err
}

func (m *defaultScoreModel) Update(ctx context.Context, data *Score) error {
	scoreDataIdKey := fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, scoreRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ContributionId, data.DeveloperId, data.Score, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt, data.DataId)
	}, scoreDataIdKey)
	return err
}

func (m *defaultScoreModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, primary)
}

func (m *defaultScoreModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", scoreRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultScoreModel) tableName() string {
	return m.table
}
