// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package analysis

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	scoreFieldNames          = builder.RawFieldNames(&Score{})
	scoreRows                = strings.Join(scoreFieldNames, ",")
	scoreRowsExpectAutoSet   = strings.Join(stringx.Remove(scoreFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	scoreRowsWithPlaceHolder = strings.Join(stringx.Remove(scoreFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheScoreDataIdPrefix      = "cache:score:dataId:"
	cacheScoreDeveloperIdPrefix = "cache:score:developerId:"
)

type (
	scoreModel interface {
		Insert(ctx context.Context, data *Score) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*Score, error)
		FindOneByDeveloperId(ctx context.Context, developerId int64) (*Score, error)
		Update(ctx context.Context, data *Score) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultScoreModel struct {
		sqlc.CachedConn
		table string
	}

	Score struct {
		DataId      int64        `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId int64        `db:"developer_id"` // Unique GitHub User ID
		Score       float64      `db:"score"`        // score
		CreatedAt   time.Time    `db:"created_at"`
		UpdatedAt   time.Time    `db:"updated_at"` // update data time
		DeletedAt   sql.NullTime `db:"deleted_at"`
	}
)

func newScoreModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultScoreModel {
	return &defaultScoreModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`score`",
	}
}

func (m *defaultScoreModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	scoreDataIdKey := fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, dataId)
	scoreDeveloperIdKey := fmt.Sprintf("%s%v", cacheScoreDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, scoreDataIdKey, scoreDeveloperIdKey)
	return err
}

func (m *defaultScoreModel) FindOne(ctx context.Context, dataId int64) (*Score, error) {
	scoreDataIdKey := fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, dataId)
	var resp Score
	err := m.QueryRowCtx(ctx, &resp, scoreDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", scoreRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScoreModel) FindOneByDeveloperId(ctx context.Context, developerId int64) (*Score, error) {
	scoreDeveloperIdKey := fmt.Sprintf("%s%v", cacheScoreDeveloperIdPrefix, developerId)
	var resp Score
	err := m.QueryRowIndexCtx(ctx, &resp, scoreDeveloperIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `developer_id` = ? limit 1", scoreRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, developerId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScoreModel) Insert(ctx context.Context, data *Score) (sql.Result, error) {
	scoreDataIdKey := fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, data.DataId)
	scoreDeveloperIdKey := fmt.Sprintf("%s%v", cacheScoreDeveloperIdPrefix, data.DeveloperId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, scoreRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.Score, data.DeletedAt)
	}, scoreDataIdKey, scoreDeveloperIdKey)
	return ret, err
}

func (m *defaultScoreModel) Update(ctx context.Context, newData *Score) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	scoreDataIdKey := fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, data.DataId)
	scoreDeveloperIdKey := fmt.Sprintf("%s%v", cacheScoreDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, scoreRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeveloperId, newData.Score, newData.DeletedAt, newData.DataId)
	}, scoreDataIdKey, scoreDeveloperIdKey)
	return err
}

func (m *defaultScoreModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheScoreDataIdPrefix, primary)
}

func (m *defaultScoreModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", scoreRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultScoreModel) tableName() string {
	return m.table
}
