// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package analysis

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	summaryFieldNames          = builder.RawFieldNames(&Summary{})
	summaryRows                = strings.Join(summaryFieldNames, ",")
	summaryRowsExpectAutoSet   = strings.Join(stringx.Remove(summaryFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	summaryRowsWithPlaceHolder = strings.Join(stringx.Remove(summaryFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSummaryDataIdPrefix      = "cache:summary:dataId:"
	cacheSummaryDeveloperIdPrefix = "cache:summary:developerId:"
)

type (
	summaryModel interface {
		Insert(ctx context.Context, data *Summary) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*Summary, error)
		FindOneByDeveloperId(ctx context.Context, developerId int64) (*Summary, error)
		Update(ctx context.Context, data *Summary) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultSummaryModel struct {
		sqlc.CachedConn
		table string
	}

	Summary struct {
		DataId      int64        `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId int64        `db:"developer_id"` // Unique GitHub User ID
		Summary     string       `db:"summary"`      // User Summary
		CreatedAt   time.Time    `db:"created_at"`
		UpdatedAt   time.Time    `db:"updated_at"` // update data time
		DeletedAt   sql.NullTime `db:"deleted_at"`
	}
)

func newSummaryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSummaryModel {
	return &defaultSummaryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`summary`",
	}
}

func (m *defaultSummaryModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	summaryDataIdKey := fmt.Sprintf("%s%v", cacheSummaryDataIdPrefix, dataId)
	summaryDeveloperIdKey := fmt.Sprintf("%s%v", cacheSummaryDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, summaryDataIdKey, summaryDeveloperIdKey)
	return err
}

func (m *defaultSummaryModel) FindOne(ctx context.Context, dataId int64) (*Summary, error) {
	summaryDataIdKey := fmt.Sprintf("%s%v", cacheSummaryDataIdPrefix, dataId)
	var resp Summary
	err := m.QueryRowCtx(ctx, &resp, summaryDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", summaryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSummaryModel) FindOneByDeveloperId(ctx context.Context, developerId int64) (*Summary, error) {
	summaryDeveloperIdKey := fmt.Sprintf("%s%v", cacheSummaryDeveloperIdPrefix, developerId)
	var resp Summary
	err := m.QueryRowIndexCtx(ctx, &resp, summaryDeveloperIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `developer_id` = ? limit 1", summaryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, developerId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSummaryModel) Insert(ctx context.Context, data *Summary) (sql.Result, error) {
	summaryDataIdKey := fmt.Sprintf("%s%v", cacheSummaryDataIdPrefix, data.DataId)
	summaryDeveloperIdKey := fmt.Sprintf("%s%v", cacheSummaryDeveloperIdPrefix, data.DeveloperId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, summaryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.Summary, data.DeletedAt)
	}, summaryDataIdKey, summaryDeveloperIdKey)
	return ret, err
}

func (m *defaultSummaryModel) Update(ctx context.Context, newData *Summary) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	summaryDataIdKey := fmt.Sprintf("%s%v", cacheSummaryDataIdPrefix, data.DataId)
	summaryDeveloperIdKey := fmt.Sprintf("%s%v", cacheSummaryDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, summaryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeveloperId, newData.Summary, newData.DeletedAt, newData.DataId)
	}, summaryDataIdKey, summaryDeveloperIdKey)
	return err
}

func (m *defaultSummaryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSummaryDataIdPrefix, primary)
}

func (m *defaultSummaryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", summaryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSummaryModel) tableName() string {
	return m.table
}
