services:
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=aster
            - MYSQL_USER=aster
            - MYSQL_PASSWORD=aster
            - TZ=Asia/Shanghai
        volumes:
            - ../config/sql:/docker-entrypoint-initdb.d/
            - ./data/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - aster

    redis:
        container_name: redis
        image: "redis:latest"
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./data/redis:/data
        environment:
            - REDIS_PASSWORD=aster
            - ALLOW_EMPTY_PASSWORD=no
        networks:
            - aster

    rabbitmq:
        container_name: rabiitmq
        image: "rabbitmq:latest"
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=aster
            - RABBITMQ_DEFAULT_PASS=aster
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq
        networks:
            - aster

    elasticsearch:
        image: elasticsearch:8.4.2
        container_name: elasticsearch
        environment:
            bootstrap.memory_lock: "true"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            discovery.type: single-node
            ingest.geoip.downloader.enabled: "false"
            TZ: Asia/Shanghai
            xpack.security.enabled: "false"
        healthcheck:
            test: ["CMD-SHELL", "curl -sf http://elasticsearch:9200/_cluster/health || exit 1"] # ⼼跳检测，成功之后不再执⾏后⾯的退出
            interval: 60s # ⼼跳检测间隔周期
            timeout: 10s
            retries: 3
            start_period: 60s # ⾸次检测延迟时间
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ../config/elasticsearch:/usr/share/elasticsearch/config
            - ./data/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        restart: always
        networks:
            - aster

    kibana:
        image: kibana:8.4.2
        container_name: kibana
        environment:
            - I18N_LOCALE=zh-CN
            - XPACK_GRAPH_ENABLED=true
            - TIMELION_ENABLED=true
            - XPACK_MONITORING_COLLECTION_ENABLED="true"
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
        volumes:
            - ../config/kibana:/usr/share/kibana/config
            - ./data/kibana:/usr/share/kibana/data
        networks:
            - aster

networks:
    aster:
        driver: bridge
        name: aster