FROM golang:1.23 AS builder

LABEL stage=gobuilder

# 设置环境变量
ENV TZ=Asia/Shanghai
ENV CGO_ENABLED=0
ENV GOPROXY=https://goproxy.cn,direct
ENV GOOS=linux
ENV GOARCH=amd64
ENV GOCACHE=/root/.cache/go-build

WORKDIR /build

ADD go.mod .
ADD go.sum .
RUN go mod download
COPY . .
COPY ./docker/etc /app/rpc/api_processor/etc
RUN --mount=type=cache,target="/root/.cache/go-build" go build -ldflags="-s -w" -o /app/api_processor ./rpc/api_processor

FROM alpine:latest
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai

# 换源，更新软件依赖
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk update --no-cache && apk add --no-cache tzdata

WORKDIR /app
COPY --from=builder /app/api_processor /app/api_processor
COPY --from=builder /app/rpc/api_processor/etc /app/rpc/api_processor/etc

CMD ["./api_processor","-f", "rpc/api_processor/etc/api_processor.yaml"]
