services:
  redis:
    container_name: aster-redis
    hostname: redis
    image: redis:bookworm # 选择使用 redis 官方的 bookworm tag
    ports:
      - "6379:6379"
    env_file:
      - "./env/redis.env"
    volumes:
      - ./data/redis:/data
    networks:
      - aster

  mysql:
    container_name: aster-mysql
    hostname: mysql
    image: mysql:9.0.1 # 选择使用 mysql 官方的 9.0.1 版本
    ports:
      - "3306:3306"
    env_file:
      - "./env/mysql.env"
    volumes:
      - ../config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ../config/mysql/mysql.cnf:/etc/mysql/conf.d/slowlog.cnf
      - ../log/sql:/var/log/mysql
    networks:
      - aster

  etcd:
    container_name: aster-etcd
    hostname: etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    env_file:
      - "./env/etcd.env"
    volumes:
      - ./data/etcd:/etcd-data
    networks:
      - aster

  etcd-keeper:
    container_name: aster-etcdkeeper
    image: evildecay/etcdkeeper
    env_file:
      - "./env/etcd-keeper.env"
    ports:
      - 8099:8080
    depends_on:
      - etcd
    networks:
      - aster

  zookeeper:
    container_name: aster-zookeeper
    hostname: zookeeper
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
      - ./data/zookeeper/logs:/logs
    networks:
      - aster

  kafka:
    container_name: aster-kafka
    hostname: kafka
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - 9092:9092
    env_file:
      - "./env/kafka.env"
    volumes:
      - ./data/kafka:/kafka
    depends_on:
      - zookeeper
    networks:
      - aster
      
  kafka-ui:
    container_name: aster-kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "9091:8080"
    env_file:
      - ./env/kafka-ui.env
    networks:
      - aster

  # elasticsearch:
  #   image: elasticsearch:8.17.1
  #   container_name: aster-elasticsearch
  #   ports:
  #     - "9200:9200"
  #   env_file:
  #     - "./env/es.env"
  #   healthcheck:
  #     test: [ "CMD-SHELL", "curl -sf http://elasticsearch:9200/_cluster/health || exit 1" ] # ⼼跳检测，成功之后不再执⾏后⾯的退出
  #     interval: 60s # ⼼跳检测间隔周期
  #     timeout: 10s
  #     retries: 3
  #     start_period: 60s # ⾸次检测延迟时间
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ../config/elasticsearch:/usr/share/elasticsearch/config 
  #     - ./data/elasticsearch:/usr/share/elasticsearch/data
  #   restart: always
  #   networks:
  #     - aster

  # kibana:
  #   image: kibana:8.17.1
  #   container_name: aster-kibana
  #   env_file:
  #     - "./env/kibana.env"
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -I http://localhost:5601 || exit 1"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "5601:5601"
  #   volumes:
  #     - ../config/kibana:/usr/share/kibana/config
  #   networks:
  #     - aster

  filebeat: # 权限问题执行 sudo chmod go-w (挂载目录)/filebeat.yml
    image: elastic/filebeat:8.17.1
    container_name: aster-filebeat
    user: root
    volumes:
      - ../config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml # 挂载配置文件
      - ./data/filebeat:/usr/share/filebeat/data  # 持久化注册表文件
      - ../log:/usr/share/filebeat/logs  # 挂载日志目录
    depends_on:
      - openobserve
    restart: on-failure
    networks:
      - aster

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.15.0-rc1
    container_name: aster-openobserve
    restart: always
    env_file:
      - ./env/openobserve.env
    ports:
      - "5080:5080"
    volumes:
      - ./data/openobserve:/data
    networks:
      - aster

  jaeger:
    container_name: aster-jaeger
    hostname: jaeger
    image: "jaegertracing/all-in-one:latest"
    restart: always
    ports:
      - 16686:16686
      - 14268:14268
      - 6831:6831/udp
    volumes:
      - ./data/jaeger:/var/lib/jaeger
      - ../config/jaeger:/etc/jaeger
    networks:
      - aster

  prometheus:
    image: prom/prometheus
    container_name: aster-prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - aster

  grafana:
    image: grafana/grafana
    container_name: aster-grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../config/grafana:/etc/grafana
    networks:
      - aster

  alertmanager: #预警模块
    image: prom/alertmanager
    container_name: aster-alertmanager
    restart: always
    ports:
      - 9193:9093
    networks:
      - aster

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: aster-node-exporter
    restart: always
    ports:
      - 9100:9100
    networks:
      - aster

  cadvisor:
    image: zcube/cadvisor:latest # 静态编译版本，兼容性更好
    container_name: aster-cadvisor
    restart: always
    platform: linux/amd64
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 8899:8080
    networks:
      - aster

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: aster-redis-exporter
    restart: always
    ports:
      - 9121:9121
    command:
      - "--redis.addr=redis://redis:6379"
    networks:
      - aster

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: aster-mysql-exporter
    restart: always
    ports:
      - 9104:9104
    command:
      - "--mysqld.username=aster:aster"
      - "--mysqld.address=mysql:3306"
    environment:
      DATA_SOURCE_NAME: 'aster:aster@(mysql:3306)/'
    depends_on:
      - mysql
    networks:
      - aster

  asynqmon:
    image: hibiken/asynqmon:latest  # 使用最新版
    container_name: aster-asynqmon-dashboard
    restart: always
    ports:
      - 6380:8080 
    env_file:
      - "./env/asynqmon.env"
    depends_on:
      - redis
    networks:
      - aster

networks:
  aster:
    driver: bridge
    name: aster