// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package relation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	createdRepoUpdatedAtFieldNames          = builder.RawFieldNames(&CreatedRepoUpdatedAt{})
	createdRepoUpdatedAtRows                = strings.Join(createdRepoUpdatedAtFieldNames, ",")
	createdRepoUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(createdRepoUpdatedAtFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	createdRepoUpdatedAtRowsWithPlaceHolder = strings.Join(stringx.Remove(createdRepoUpdatedAtFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCreatedRepoUpdatedAtDataIdPrefix = "cache:createdRepoUpdatedAt:dataId:"
)

type (
	createdRepoUpdatedAtModel interface {
		Insert(ctx context.Context, data *CreatedRepoUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*CreatedRepoUpdatedAt, error)
		Update(ctx context.Context, data *CreatedRepoUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultCreatedRepoUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	CreatedRepoUpdatedAt struct {
		DataId        int64     `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId   int64     `db:"developer_id"` // Unique GitHub User ID
		DataCreatedAt time.Time `db:"data_created_at"`
		DataUpdatedAt time.Time `db:"data_updated_at"` // update data time
	}
)

func newCreatedRepoUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCreatedRepoUpdatedAtModel {
	return &defaultCreatedRepoUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`created_repo_updated_at`",
	}
}

func (m *defaultCreatedRepoUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	createdRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheCreatedRepoUpdatedAtDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, createdRepoUpdatedAtDataIdKey)
	return err
}

func (m *defaultCreatedRepoUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*CreatedRepoUpdatedAt, error) {
	createdRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheCreatedRepoUpdatedAtDataIdPrefix, dataId)
	var resp CreatedRepoUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, createdRepoUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", createdRepoUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCreatedRepoUpdatedAtModel) Insert(ctx context.Context, data *CreatedRepoUpdatedAt) (sql.Result, error) {
	createdRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheCreatedRepoUpdatedAtDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, createdRepoUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt)
	}, createdRepoUpdatedAtDataIdKey)
	return ret, err
}

func (m *defaultCreatedRepoUpdatedAtModel) Update(ctx context.Context, data *CreatedRepoUpdatedAt) error {
	createdRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheCreatedRepoUpdatedAtDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, createdRepoUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt, data.DataId)
	}, createdRepoUpdatedAtDataIdKey)
	return err
}

func (m *defaultCreatedRepoUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCreatedRepoUpdatedAtDataIdPrefix, primary)
}

func (m *defaultCreatedRepoUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", createdRepoUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCreatedRepoUpdatedAtModel) tableName() string {
	return m.table
}
