// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package relation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	createRepoFieldNames          = builder.RawFieldNames(&CreateRepo{})
	createRepoRows                = strings.Join(createRepoFieldNames, ",")
	createRepoRowsExpectAutoSet   = strings.Join(stringx.Remove(createRepoFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	createRepoRowsWithPlaceHolder = strings.Join(stringx.Remove(createRepoFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCreateRepoDataIdPrefix = "cache:createRepo:dataId:"
)

type (
	createRepoModel interface {
		Insert(ctx context.Context, data *CreateRepo) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*CreateRepo, error)
		Update(ctx context.Context, data *CreateRepo) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultCreateRepoModel struct {
		sqlc.CachedConn
		table string
	}

	CreateRepo struct {
		DataId        int64        `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId   int64        `db:"developer_id"` // Unique GitHub User ID
		RepoId        int64        `db:"repo_id"`      // Unique GitHub Repository ID
		DataCreatedAt time.Time    `db:"data_created_at"`
		DataUpdatedAt time.Time    `db:"data_updated_at"` // update data time
		DataDeletedAt sql.NullTime `db:"data_deleted_at"`
	}
)

func newCreateRepoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCreateRepoModel {
	return &defaultCreateRepoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`create_repo`",
	}
}

func (m *defaultCreateRepoModel) Delete(ctx context.Context, dataId int64) error {
	createRepoDataIdKey := fmt.Sprintf("%s%v", cacheCreateRepoDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, createRepoDataIdKey)
	return err
}

func (m *defaultCreateRepoModel) FindOne(ctx context.Context, dataId int64) (*CreateRepo, error) {
	createRepoDataIdKey := fmt.Sprintf("%s%v", cacheCreateRepoDataIdPrefix, dataId)
	var resp CreateRepo
	err := m.QueryRowCtx(ctx, &resp, createRepoDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", createRepoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCreateRepoModel) Insert(ctx context.Context, data *CreateRepo) (sql.Result, error) {
	createRepoDataIdKey := fmt.Sprintf("%s%v", cacheCreateRepoDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, createRepoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.RepoId, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt)
	}, createRepoDataIdKey)
	return ret, err
}

func (m *defaultCreateRepoModel) Update(ctx context.Context, data *CreateRepo) error {
	createRepoDataIdKey := fmt.Sprintf("%s%v", cacheCreateRepoDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, createRepoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeveloperId, data.RepoId, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt, data.DataId)
	}, createRepoDataIdKey)
	return err
}

func (m *defaultCreateRepoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCreateRepoDataIdPrefix, primary)
}

func (m *defaultCreateRepoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", createRepoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCreateRepoModel) tableName() string {
	return m.table
}
