// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package relation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followingUpdatedAtFieldNames          = builder.RawFieldNames(&FollowingUpdatedAt{})
	followingUpdatedAtRows                = strings.Join(followingUpdatedAtFieldNames, ",")
	followingUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(followingUpdatedAtFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followingUpdatedAtRowsWithPlaceHolder = strings.Join(stringx.Remove(followingUpdatedAtFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFollowingUpdatedAtDataIdPrefix = "cache:followingUpdatedAt:dataId:"
)

type (
	followingUpdatedAtModel interface {
		Insert(ctx context.Context, data *FollowingUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*FollowingUpdatedAt, error)
		Update(ctx context.Context, data *FollowingUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultFollowingUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	FollowingUpdatedAt struct {
		DataId        int64     `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId   int64     `db:"developer_id"` // Unique GitHub User ID
		DataCreatedAt time.Time `db:"data_created_at"`
		DataUpdatedAt time.Time `db:"data_updated_at"` // update data time
	}
)

func newFollowingUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFollowingUpdatedAtModel {
	return &defaultFollowingUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`following_updated_at`",
	}
}

func (m *defaultFollowingUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	followingUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheFollowingUpdatedAtDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, followingUpdatedAtDataIdKey)
	return err
}

func (m *defaultFollowingUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*FollowingUpdatedAt, error) {
	followingUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheFollowingUpdatedAtDataIdPrefix, dataId)
	var resp FollowingUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, followingUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", followingUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowingUpdatedAtModel) Insert(ctx context.Context, data *FollowingUpdatedAt) (sql.Result, error) {
	followingUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheFollowingUpdatedAtDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, followingUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt)
	}, followingUpdatedAtDataIdKey)
	return ret, err
}

func (m *defaultFollowingUpdatedAtModel) Update(ctx context.Context, data *FollowingUpdatedAt) error {
	followingUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheFollowingUpdatedAtDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, followingUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt, data.DataId)
	}, followingUpdatedAtDataIdKey)
	return err
}

func (m *defaultFollowingUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFollowingUpdatedAtDataIdPrefix, primary)
}

func (m *defaultFollowingUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", followingUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFollowingUpdatedAtModel) tableName() string {
	return m.table
}
