// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package relation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followerUpdatedAtFieldNames          = builder.RawFieldNames(&FollowerUpdatedAt{})
	followerUpdatedAtRows                = strings.Join(followerUpdatedAtFieldNames, ",")
	followerUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(followerUpdatedAtFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followerUpdatedAtRowsWithPlaceHolder = strings.Join(stringx.Remove(followerUpdatedAtFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFollowerUpdatedAtDataIdPrefix = "cache:followerUpdatedAt:dataId:"
)

type (
	followerUpdatedAtModel interface {
		Insert(ctx context.Context, data *FollowerUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*FollowerUpdatedAt, error)
		Update(ctx context.Context, data *FollowerUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultFollowerUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	FollowerUpdatedAt struct {
		DataId        int64     `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId   int64     `db:"developer_id"` // Unique GitHub User ID
		DataCreatedAt time.Time `db:"data_created_at"`
		DataUpdatedAt time.Time `db:"data_updated_at"` // update data time
	}
)

func newFollowerUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFollowerUpdatedAtModel {
	return &defaultFollowerUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`follower_updated_at`",
	}
}

func (m *defaultFollowerUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	followerUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheFollowerUpdatedAtDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, followerUpdatedAtDataIdKey)
	return err
}

func (m *defaultFollowerUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*FollowerUpdatedAt, error) {
	followerUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheFollowerUpdatedAtDataIdPrefix, dataId)
	var resp FollowerUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, followerUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", followerUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowerUpdatedAtModel) Insert(ctx context.Context, data *FollowerUpdatedAt) (sql.Result, error) {
	followerUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheFollowerUpdatedAtDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, followerUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt)
	}, followerUpdatedAtDataIdKey)
	return ret, err
}

func (m *defaultFollowerUpdatedAtModel) Update(ctx context.Context, data *FollowerUpdatedAt) error {
	followerUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheFollowerUpdatedAtDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, followerUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt, data.DataId)
	}, followerUpdatedAtDataIdKey)
	return err
}

func (m *defaultFollowerUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFollowerUpdatedAtDataIdPrefix, primary)
}

func (m *defaultFollowerUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", followerUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFollowerUpdatedAtModel) tableName() string {
	return m.table
}
