// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package relation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forkUpdatedAtFieldNames          = builder.RawFieldNames(&ForkUpdatedAt{})
	forkUpdatedAtRows                = strings.Join(forkUpdatedAtFieldNames, ",")
	forkUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(forkUpdatedAtFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forkUpdatedAtRowsWithPlaceHolder = strings.Join(stringx.Remove(forkUpdatedAtFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheForkUpdatedAtDataIdPrefix = "cache:forkUpdatedAt:dataId:"
)

type (
	forkUpdatedAtModel interface {
		Insert(ctx context.Context, data *ForkUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*ForkUpdatedAt, error)
		Update(ctx context.Context, data *ForkUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultForkUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	ForkUpdatedAt struct {
		DataId        int64     `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId   int64     `db:"developer_id"` // Unique GitHub User ID
		DataCreatedAt time.Time `db:"data_created_at"`
		DataUpdatedAt time.Time `db:"data_updated_at"` // update data time
	}
)

func newForkUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultForkUpdatedAtModel {
	return &defaultForkUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`fork_updated_at`",
	}
}

func (m *defaultForkUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	forkUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheForkUpdatedAtDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, forkUpdatedAtDataIdKey)
	return err
}

func (m *defaultForkUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*ForkUpdatedAt, error) {
	forkUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheForkUpdatedAtDataIdPrefix, dataId)
	var resp ForkUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, forkUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", forkUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForkUpdatedAtModel) Insert(ctx context.Context, data *ForkUpdatedAt) (sql.Result, error) {
	forkUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheForkUpdatedAtDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, forkUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt)
	}, forkUpdatedAtDataIdKey)
	return ret, err
}

func (m *defaultForkUpdatedAtModel) Update(ctx context.Context, data *ForkUpdatedAt) error {
	forkUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheForkUpdatedAtDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, forkUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt, data.DataId)
	}, forkUpdatedAtDataIdKey)
	return err
}

func (m *defaultForkUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheForkUpdatedAtDataIdPrefix, primary)
}

func (m *defaultForkUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", forkUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultForkUpdatedAtModel) tableName() string {
	return m.table
}
