// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package relation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forkFieldNames          = builder.RawFieldNames(&Fork{})
	forkRows                = strings.Join(forkFieldNames, ",")
	forkRowsExpectAutoSet   = strings.Join(stringx.Remove(forkFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forkRowsWithPlaceHolder = strings.Join(stringx.Remove(forkFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheForkDataIdPrefix = "cache:fork:dataId:"
)

type (
	forkModel interface {
		Insert(ctx context.Context, data *Fork) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*Fork, error)
		Update(ctx context.Context, data *Fork) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultForkModel struct {
		sqlc.CachedConn
		table string
	}

	Fork struct {
		DataId         int64        `db:"data_id"`          // Generated Primary Key, Must Not Be Changed
		OriginalRepoId int64        `db:"original_repo_id"` // Original Repository ID
		ForkRepoId     int64        `db:"fork_repo_id"`     // Fork Repository ID
		DataCreatedAt  time.Time    `db:"data_created_at"`
		DataUpdatedAt  time.Time    `db:"data_updated_at"` // update data time
		DataDeletedAt  sql.NullTime `db:"data_deleted_at"`
	}
)

func newForkModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultForkModel {
	return &defaultForkModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`fork`",
	}
}

func (m *defaultForkModel) Delete(ctx context.Context, dataId int64) error {
	forkDataIdKey := fmt.Sprintf("%s%v", cacheForkDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, forkDataIdKey)
	return err
}

func (m *defaultForkModel) FindOne(ctx context.Context, dataId int64) (*Fork, error) {
	forkDataIdKey := fmt.Sprintf("%s%v", cacheForkDataIdPrefix, dataId)
	var resp Fork
	err := m.QueryRowCtx(ctx, &resp, forkDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", forkRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForkModel) Insert(ctx context.Context, data *Fork) (sql.Result, error) {
	forkDataIdKey := fmt.Sprintf("%s%v", cacheForkDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, forkRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.OriginalRepoId, data.ForkRepoId, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt)
	}, forkDataIdKey)
	return ret, err
}

func (m *defaultForkModel) Update(ctx context.Context, data *Fork) error {
	forkDataIdKey := fmt.Sprintf("%s%v", cacheForkDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, forkRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.OriginalRepoId, data.ForkRepoId, data.DataCreatedAt, data.DataUpdatedAt, data.DataDeletedAt, data.DataId)
	}, forkDataIdKey)
	return err
}

func (m *defaultForkModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheForkDataIdPrefix, primary)
}

func (m *defaultForkModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", forkRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultForkModel) tableName() string {
	return m.table
}
