// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package relation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	starredRepoUpdatedAtFieldNames          = builder.RawFieldNames(&StarredRepoUpdatedAt{})
	starredRepoUpdatedAtRows                = strings.Join(starredRepoUpdatedAtFieldNames, ",")
	starredRepoUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(starredRepoUpdatedAtFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	starredRepoUpdatedAtRowsWithPlaceHolder = strings.Join(stringx.Remove(starredRepoUpdatedAtFieldNames, "`data_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheStarredRepoUpdatedAtDataIdPrefix = "cache:starredRepoUpdatedAt:dataId:"
)

type (
	starredRepoUpdatedAtModel interface {
		Insert(ctx context.Context, data *StarredRepoUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*StarredRepoUpdatedAt, error)
		Update(ctx context.Context, data *StarredRepoUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultStarredRepoUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	StarredRepoUpdatedAt struct {
		DataId        int64     `db:"data_id"`      // Generated Primary Key, Must Not Be Changed
		DeveloperId   int64     `db:"developer_id"` // Unique GitHub User ID
		DataCreatedAt time.Time `db:"data_created_at"`
		DataUpdatedAt time.Time `db:"data_updated_at"` // update data time
	}
)

func newStarredRepoUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultStarredRepoUpdatedAtModel {
	return &defaultStarredRepoUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`starred_repo_updated_at`",
	}
}

func (m *defaultStarredRepoUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	starredRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheStarredRepoUpdatedAtDataIdPrefix, dataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `data_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, starredRepoUpdatedAtDataIdKey)
	return err
}

func (m *defaultStarredRepoUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*StarredRepoUpdatedAt, error) {
	starredRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheStarredRepoUpdatedAtDataIdPrefix, dataId)
	var resp StarredRepoUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, starredRepoUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", starredRepoUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStarredRepoUpdatedAtModel) Insert(ctx context.Context, data *StarredRepoUpdatedAt) (sql.Result, error) {
	starredRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheStarredRepoUpdatedAtDataIdPrefix, data.DataId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, starredRepoUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataId, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt)
	}, starredRepoUpdatedAtDataIdKey)
	return ret, err
}

func (m *defaultStarredRepoUpdatedAtModel) Update(ctx context.Context, data *StarredRepoUpdatedAt) error {
	starredRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheStarredRepoUpdatedAtDataIdPrefix, data.DataId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `data_id` = ?", m.table, starredRepoUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeveloperId, data.DataCreatedAt, data.DataUpdatedAt, data.DataId)
	}, starredRepoUpdatedAtDataIdKey)
	return err
}

func (m *defaultStarredRepoUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheStarredRepoUpdatedAtDataIdPrefix, primary)
}

func (m *defaultStarredRepoUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `data_id` = ? limit 1", starredRepoUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultStarredRepoUpdatedAtModel) tableName() string {
	return m.table
}
