// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: repo.proto

package repoclient

import (
	"context"

	"github.com/wushiling50/aster/gen/repo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRepoReq      = repo.AddRepoReq
	AddRepoResp     = repo.AddRepoResp
	DelRepoByIdReq  = repo.DelRepoByIdReq
	DelRepoByIdResp = repo.DelRepoByIdResp
	GetRepoByIdReq  = repo.GetRepoByIdReq
	GetRepoByIdResp = repo.GetRepoByIdResp
	Repo            = repo.Repo
	UpdateRepoReq   = repo.UpdateRepoReq
	UpdateRepoResp  = repo.UpdateRepoResp

	RepoZrpcClient interface {
		AddRepo(ctx context.Context, in *AddRepoReq, opts ...grpc.CallOption) (*AddRepoResp, error)
		UpdateRepo(ctx context.Context, in *UpdateRepoReq, opts ...grpc.CallOption) (*UpdateRepoResp, error)
		DelRepoById(ctx context.Context, in *DelRepoByIdReq, opts ...grpc.CallOption) (*DelRepoByIdResp, error)
		GetRepoById(ctx context.Context, in *GetRepoByIdReq, opts ...grpc.CallOption) (*GetRepoByIdResp, error)
	}

	defaultRepoZrpcClient struct {
		cli zrpc.Client
	}
)

func NewRepoZrpcClient(cli zrpc.Client) RepoZrpcClient {
	return &defaultRepoZrpcClient{
		cli: cli,
	}
}

func (m *defaultRepoZrpcClient) AddRepo(ctx context.Context, in *AddRepoReq, opts ...grpc.CallOption) (*AddRepoResp, error) {
	client := repo.NewRepoClient(m.cli.Conn())
	return client.AddRepo(ctx, in, opts...)
}

func (m *defaultRepoZrpcClient) UpdateRepo(ctx context.Context, in *UpdateRepoReq, opts ...grpc.CallOption) (*UpdateRepoResp, error) {
	client := repo.NewRepoClient(m.cli.Conn())
	return client.UpdateRepo(ctx, in, opts...)
}

func (m *defaultRepoZrpcClient) DelRepoById(ctx context.Context, in *DelRepoByIdReq, opts ...grpc.CallOption) (*DelRepoByIdResp, error) {
	client := repo.NewRepoClient(m.cli.Conn())
	return client.DelRepoById(ctx, in, opts...)
}

func (m *defaultRepoZrpcClient) GetRepoById(ctx context.Context, in *GetRepoByIdReq, opts ...grpc.CallOption) (*GetRepoByIdResp, error) {
	client := repo.NewRepoClient(m.cli.Conn())
	return client.GetRepoById(ctx, in, opts...)
}
