services:
  api:
    name: api
    load-balance: false
    addr:
      - 127.0.0.1:10001

snowflake:
  worker-id: 0
  datancenter-id: 0

mysql:
  addr: 127.0.0.1:3306
  database: aster
  username: aster
  password: aster
  charset: utf8mb4

redis:
  addr: 127.0.0.1:6379
  password: aster

rabbitmq:
  addr: 127.0.0.1:5672
  username: aster
  password: aster

elasticsearch:
  addr: 127.0.0.1:9200
  host: 127.0.0.1
