// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _asterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _talentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rankMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _talentrankMw() []app.HandlerFunc {
	// your code...
	return nil
}
