syntax = "proto3";

package developer;

option go_package ="github.com/wushiling50/aster/gen/developer";

import "idl/base.proto";

// ====== Developer ======
message Developer {
    int64 id = 1; // Unique id of GitHub user.
    string name = 2; // name
    string login = 3; // login
    string avatarUrl = 4; // avatarUrl
    string company = 5; // company
    string location = 6; // location
    string bio = 7; // bio
    string blog = 8; // blog
    string email = 9; // email
    string twitterUsername = 10; // twitterUsername
    int64 repos = 11; // repo_count
    int64 following = 12; // following_count
    int64 followers = 13; // followers_count
    int64 stars = 14; // star_count
    int64 gists = 15; // gists_count
}

message AddDeveloperReq {
    Developer developer = 1;
}

message AddDeveloperResp {
    base.Base base = 1;
}

message UpdateDeveloperReq {
    Developer developer = 1;
}

message UpdateDeveloperResp {
    base.Base base = 1;
}

message GetDeveloperByIdReq {
    int64 id = 1; // id
}

message GetDeveloperByIdResp {
    base.Base base = 1;
    Developer developer = 2; // developer
}

message GetDeveloperByLoginReq {
    string login = 1; //login
}

message GetDeveloperByLoginResp {
    base.Base base = 1;
    Developer developer = 2; // developer
}

service developer{
    rpc AddDeveloper(AddDeveloperReq) returns (AddDeveloperResp);
    rpc UpdateDeveloper(UpdateDeveloperReq) returns (UpdateDeveloperResp);
    rpc GetDeveloperById(GetDeveloperByIdReq) returns (GetDeveloperByIdResp);
    rpc GetDeveloperByLogin(GetDeveloperByLoginReq) returns (GetDeveloperByLoginResp);
}