syntax = "proto3";

package relation;

option go_package ="github.com/wushiling50/aster/gen/relation";

import "idl/base.proto";

// ====== Relation ======

// ====== CreateRepo ======
message CreateRepo {
    int64 dataId = 1; // dataId
    int64 developerId = 2; // developerId
    int64 repoId = 3; // repoId
}

message AddCreateRepoReq {
    int64 developerId = 1; // developerId
    int64 repoId = 2; // repoId
}

message AddCreateRepoResp {
    base.Base base = 1;
}

message SearchCreatedRepoReq {
    int64 page = 1; // page
    int64 limit = 2; // limit
    int64 developerId = 3; // developerId
}

message SearchCreatedRepoResp {
    base.Base base = 1;
    repeated int64 repoIds = 2; // repoId
}

message DelAllCreatedRepoReq {
    int64 developerId = 1; //developerId
}
  
message DelAllCreatedRepoResp {
    base.Base base = 1;
}

// ====== Follow ======
message Follow {
    int64 dataId = 1; // dataId
    int64 followerId = 2; // followerId
    int64 followingId = 3; // followingId
}

message AddFollowReq {
    int64 followerId = 1; // followerId
    int64 followingId = 2; // followingId
}

message AddFollowResp {
    base.Base base = 1;
}

message SearchFollowingByDeveloperIdReq {
    int64 page = 1; // page
    int64 limit = 2; // limit
    int64 developerId = 3; // followerId
}

message SearchFollowingByDeveloperIdResp {
    base.Base base = 1;
    repeated int64 followingIds = 2; // followingId
}

message SearchFollowerByDeveloperIdReq {
    int64 page = 1; // page
    int64 limit = 2; // limit
    int64 developerId = 3; // followingId
}

message SearchFollowerByDeveloperIdResp {
    base.Base base = 1;
    repeated int64 followerIds = 2; // followerId
}

message DelAllFollowerReq {
    int64 developerId = 1; //developerId
}
  
message DelAllFollowerResp {
    base.Base base = 1;
}
  
message DelAllFollowingReq {
    int64 developerId = 1; //developerId
}
  
message DelAllFollowingResp {
    base.Base base = 1;
}

// ====== Star ======
message Star {
    int64 dataId = 1; // dataId
    int64 developerId = 2; // developerId
    int64 repoId = 3; // repoId
}

message AddStarReq {
    int64 developerId = 1; // developerId
    int64 repoId = 2; // repoId
}

message AddStarResp {
    base.Base base = 1;
}

message SearchStarredRepoReq {
    int64 page = 1; // page
    int64 limit = 2; // limit
    int64 developerId = 3; // developerId
}

message SearchStarredRepoResp {
    base.Base base = 1;
    repeated int64 repoIds = 2; // repoId
}

message SearchStaringDeveloperReq {
    int64 page = 1; // page
    int64 limit = 2; // limit
    int64 repoId = 3; // repoId
}

message SearchStaringDeveloperResp {
    base.Base base = 1;
    repeated int64 developerIds = 2; // developerId
}

message DelAllStarredRepoReq {
    int64 developerId = 1; //developerId
}
  
message DelAllStarredRepoResp {
    base.Base base = 1;
}
  
message DelAllStaringDeveloperReq {
    int64 repoId = 1; //repoId
}
  
message DelAllStaringDeveloperResp {
    base.Base base = 1;
}

service relation{ 
    //-----------------------CreateRepo-----------------------
    rpc AddCreateRepo(AddCreateRepoReq) returns (AddCreateRepoResp);
    rpc SearchCreatedRepo(SearchCreatedRepoReq) returns (SearchCreatedRepoResp);
    rpc DelAllCreatedRepo(DelAllCreatedRepoReq) returns (DelAllCreatedRepoResp);
    //-----------------------Follow-----------------------
    rpc AddFollow(AddFollowReq) returns (AddFollowResp);
    rpc SearchFollowingByDeveloperId(SearchFollowingByDeveloperIdReq) returns (SearchFollowingByDeveloperIdResp);
    rpc SearchFollowerByDeveloperId(SearchFollowerByDeveloperIdReq) returns (SearchFollowerByDeveloperIdResp);
    rpc DelAllFollower(DelAllFollowerReq) returns (DelAllFollowerResp);
    rpc DelAllFollowing(DelAllFollowingReq) returns (DelAllFollowingResp);
    //-----------------------Star-----------------------
    rpc AddStar(AddStarReq) returns (AddStarResp);
    rpc SearchStarredRepo(SearchStarredRepoReq) returns (SearchStarredRepoResp);
    rpc SearchStaringDeveloper(SearchStaringDeveloperReq) returns (SearchStaringDeveloperResp);
    rpc DelAllStarredRepo(DelAllStarredRepoReq) returns (DelAllStarredRepoResp);
    rpc DelAllStaringDeveloper(DelAllStaringDeveloperReq) returns (DelAllStaringDeveloperResp);
}