// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: relation.proto

package server

import (
	"context"

	"github.com/wushiling50/aster/gen/relation"
	"github.com/wushiling50/aster/rpc/relation/internal/logic"
	"github.com/wushiling50/aster/rpc/relation/internal/svc"
)

type RelationServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedRelationServer
}

func NewRelationServer(svcCtx *svc.ServiceContext) *RelationServer {
	return &RelationServer{
		svcCtx: svcCtx,
	}
}

// -----------------------CreateRepo-----------------------
func (s *RelationServer) AddCreateRepo(ctx context.Context, in *relation.AddCreateRepoReq) (*relation.AddCreateRepoResp, error) {
	l := logic.NewAddCreateRepoLogic(ctx, s.svcCtx)
	return l.AddCreateRepo(in)
}

func (s *RelationServer) SearchCreatedRepo(ctx context.Context, in *relation.SearchCreatedRepoReq) (*relation.SearchCreatedRepoResp, error) {
	l := logic.NewSearchCreatedRepoLogic(ctx, s.svcCtx)
	return l.SearchCreatedRepo(in)
}

func (s *RelationServer) DelAllCreatedRepo(ctx context.Context, in *relation.DelAllCreatedRepoReq) (*relation.DelAllCreatedRepoResp, error) {
	l := logic.NewDelAllCreatedRepoLogic(ctx, s.svcCtx)
	return l.DelAllCreatedRepo(in)
}

// -----------------------Follow-----------------------
func (s *RelationServer) AddFollow(ctx context.Context, in *relation.AddFollowReq) (*relation.AddFollowResp, error) {
	l := logic.NewAddFollowLogic(ctx, s.svcCtx)
	return l.AddFollow(in)
}

func (s *RelationServer) SearchFollowingByDeveloperId(ctx context.Context, in *relation.SearchFollowingByDeveloperIdReq) (*relation.SearchFollowingByDeveloperIdResp, error) {
	l := logic.NewSearchFollowingByDeveloperIdLogic(ctx, s.svcCtx)
	return l.SearchFollowingByDeveloperId(in)
}

func (s *RelationServer) SearchFollowerByDeveloperId(ctx context.Context, in *relation.SearchFollowerByDeveloperIdReq) (*relation.SearchFollowerByDeveloperIdResp, error) {
	l := logic.NewSearchFollowerByDeveloperIdLogic(ctx, s.svcCtx)
	return l.SearchFollowerByDeveloperId(in)
}

func (s *RelationServer) DelAllFollower(ctx context.Context, in *relation.DelAllFollowerReq) (*relation.DelAllFollowerResp, error) {
	l := logic.NewDelAllFollowerLogic(ctx, s.svcCtx)
	return l.DelAllFollower(in)
}

func (s *RelationServer) DelAllFollowing(ctx context.Context, in *relation.DelAllFollowingReq) (*relation.DelAllFollowingResp, error) {
	l := logic.NewDelAllFollowingLogic(ctx, s.svcCtx)
	return l.DelAllFollowing(in)
}

// -----------------------Fork-----------------------
func (s *RelationServer) AddFork(ctx context.Context, in *relation.AddForkReq) (*relation.AddForkResp, error) {
	l := logic.NewAddForkLogic(ctx, s.svcCtx)
	return l.AddFork(in)
}

func (s *RelationServer) GetOrigin(ctx context.Context, in *relation.GetOriginReq) (*relation.GetOriginResp, error) {
	l := logic.NewGetOriginLogic(ctx, s.svcCtx)
	return l.GetOrigin(in)
}

func (s *RelationServer) SearchFork(ctx context.Context, in *relation.SearchForkReq) (*relation.SearchForkResp, error) {
	l := logic.NewSearchForkLogic(ctx, s.svcCtx)
	return l.SearchFork(in)
}

func (s *RelationServer) DelAllFork(ctx context.Context, in *relation.DelAllForkReq) (*relation.DelAllForkResp, error) {
	l := logic.NewDelAllForkLogic(ctx, s.svcCtx)
	return l.DelAllFork(in)
}

// -----------------------Star-----------------------
func (s *RelationServer) AddStar(ctx context.Context, in *relation.AddStarReq) (*relation.AddStarResp, error) {
	l := logic.NewAddStarLogic(ctx, s.svcCtx)
	return l.AddStar(in)
}

func (s *RelationServer) SearchStarredRepo(ctx context.Context, in *relation.SearchStarredRepoReq) (*relation.SearchStarredRepoResp, error) {
	l := logic.NewSearchStarredRepoLogic(ctx, s.svcCtx)
	return l.SearchStarredRepo(in)
}

func (s *RelationServer) SearchStaringDeveloper(ctx context.Context, in *relation.SearchStaringDeveloperReq) (*relation.SearchStaringDeveloperResp, error) {
	l := logic.NewSearchStaringDeveloperLogic(ctx, s.svcCtx)
	return l.SearchStaringDeveloper(in)
}

func (s *RelationServer) DelAllStarredRepo(ctx context.Context, in *relation.DelAllStarredRepoReq) (*relation.DelAllStarredRepoResp, error) {
	l := logic.NewDelAllStarredRepoLogic(ctx, s.svcCtx)
	return l.DelAllStarredRepo(in)
}

func (s *RelationServer) DelAllStaringDev(ctx context.Context, in *relation.DelAllStaringDevReq) (*relation.DelAllStaringDevResp, error) {
	l := logic.NewDelAllStaringDevLogic(ctx, s.svcCtx)
	return l.DelAllStaringDev(in)
}
