Name: apiProcessor
Mode: dev

# dev 环境模式配置
DevServer:
  Enabled: true
  Port: 5005

# 日志配置
Log:
  ServiceName: apiProcessor
  Mode: file
  Encoding: json
  Path: log/apiProcessor/

# 链路追踪​
Telemetry:
  Name: apiProcessor
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

AsynqRedisConf:
  Addr: redis:6379
  Pass: aster
  DB: 0

# RPC 服务配置
Services:
  Analysis:
    Etcd:
      Hosts:
      - etcd:2379
      Key: analysis.rpc
    Timeout: 60000