Name: fetcher
Mode: dev

# dev 环境模式配置
DevServer:
  Enabled: true
  Port: 5008

# 日志配置
Log:
  ServiceName: fetcher
  Mode: file
  Encoding: json
  Path: log/fetcher/

# 链路追踪​
Telemetry:
  Name: fetcher
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

AsynqRedisConf:
  Addr: redis:6379
  Pass: aster
  DB: 0

KafkaQueue:
  KqDeveloperPusherConf:
    Name: developer-pusher
    Brokers:
      - kafka:9092
    Topic: developer-update

  KqContributionPusherConf:
    Name: contribution-pusher
    Brokers:
      - kafka:9092
    Topic: contribution-update

  KqCreateRepoPusherConf:
    Name: create-repo-pusher
    Brokers:
      - kafka:9092
    Topic: create-repo-update

  KqStarPusherConf:
    Name: star-pusher
    Brokers:
      - kafka:9092
    Topic: star-update

  KqFollowPusherConf:
    Name: follow-pusher
    Brokers:
      - kafka:9092
    Topic: follow-update

  KqRepoPusherConf:
    Name: repo-pusher
    Brokers:
      - kafka:9092
    Topic: repo-update


# RPC 服务配置
Services:
  Developer:
    Etcd:
      Hosts:
      - etcd:2379
      Key: developer.rpc

  Relation:
    Etcd:
      Hosts:
      - etcd:2379
      Key: relation.rpc

  Repo:
    Etcd:
      Hosts:
      - etcd:2379
      Key: repo.rpc

  Contribution:
    Etcd:
      Hosts:
      - etcd:2379
      Key: contribution.rpc