// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: contribution.proto

package contributionclient

import (
	"context"

	"github.com/wushiling50/aster/gen/contribution"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddContributionReq                            = contribution.AddContributionReq
	AddContributionResp                           = contribution.AddContributionResp
	Contribution                                  = contribution.Contribution
	DelAllContributionInCategoryByDeveloperIdReq  = contribution.DelAllContributionInCategoryByDeveloperIdReq
	DelAllContributionInCategoryByDeveloperIdResp = contribution.DelAllContributionInCategoryByDeveloperIdResp
	SearchByCategoryReq                           = contribution.SearchByCategoryReq
	SearchByCategoryResp                          = contribution.SearchByCategoryResp
	SearchByDeveloperIdReq                        = contribution.SearchByDeveloperIdReq
	SearchByDeveloperIdResp                       = contribution.SearchByDeveloperIdResp
	SearchByRepoIdReq                             = contribution.SearchByRepoIdReq
	SearchByRepoIdResp                            = contribution.SearchByRepoIdResp

	ContributionZrpcClient interface {
		AddContribution(ctx context.Context, in *AddContributionReq, opts ...grpc.CallOption) (*AddContributionResp, error)
		DelAllContributionInCategoryByDeveloperId(ctx context.Context, in *DelAllContributionInCategoryByDeveloperIdReq, opts ...grpc.CallOption) (*DelAllContributionInCategoryByDeveloperIdResp, error)
		SearchByCategory(ctx context.Context, in *SearchByCategoryReq, opts ...grpc.CallOption) (*SearchByCategoryResp, error)
		SearchByDeveloperId(ctx context.Context, in *SearchByDeveloperIdReq, opts ...grpc.CallOption) (*SearchByDeveloperIdResp, error)
		SearchByRepoId(ctx context.Context, in *SearchByRepoIdReq, opts ...grpc.CallOption) (*SearchByRepoIdResp, error)
	}

	defaultContributionZrpcClient struct {
		cli zrpc.Client
	}
)

func NewContributionZrpcClient(cli zrpc.Client) ContributionZrpcClient {
	return &defaultContributionZrpcClient{
		cli: cli,
	}
}

func (m *defaultContributionZrpcClient) AddContribution(ctx context.Context, in *AddContributionReq, opts ...grpc.CallOption) (*AddContributionResp, error) {
	client := contribution.NewContributionClient(m.cli.Conn())
	return client.AddContribution(ctx, in, opts...)
}

func (m *defaultContributionZrpcClient) DelAllContributionInCategoryByDeveloperId(ctx context.Context, in *DelAllContributionInCategoryByDeveloperIdReq, opts ...grpc.CallOption) (*DelAllContributionInCategoryByDeveloperIdResp, error) {
	client := contribution.NewContributionClient(m.cli.Conn())
	return client.DelAllContributionInCategoryByDeveloperId(ctx, in, opts...)
}

func (m *defaultContributionZrpcClient) SearchByCategory(ctx context.Context, in *SearchByCategoryReq, opts ...grpc.CallOption) (*SearchByCategoryResp, error) {
	client := contribution.NewContributionClient(m.cli.Conn())
	return client.SearchByCategory(ctx, in, opts...)
}

func (m *defaultContributionZrpcClient) SearchByDeveloperId(ctx context.Context, in *SearchByDeveloperIdReq, opts ...grpc.CallOption) (*SearchByDeveloperIdResp, error) {
	client := contribution.NewContributionClient(m.cli.Conn())
	return client.SearchByDeveloperId(ctx, in, opts...)
}

func (m *defaultContributionZrpcClient) SearchByRepoId(ctx context.Context, in *SearchByRepoIdReq, opts ...grpc.CallOption) (*SearchByRepoIdResp, error) {
	client := contribution.NewContributionClient(m.cli.Conn())
	return client.SearchByRepoId(ctx, in, opts...)
}
