// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: contribution.proto

package server

import (
	"context"

	"github.com/wushiling50/aster/gen/contribution"
	"github.com/wushiling50/aster/rpc/contribution/internal/logic"
	"github.com/wushiling50/aster/rpc/contribution/internal/svc"
)

type ContributionServer struct {
	svcCtx *svc.ServiceContext
	contribution.UnimplementedContributionServer
}

func NewContributionServer(svcCtx *svc.ServiceContext) *ContributionServer {
	return &ContributionServer{
		svcCtx: svcCtx,
	}
}

func (s *ContributionServer) AddContribution(ctx context.Context, in *contribution.AddContributionReq) (*contribution.AddContributionResp, error) {
	l := logic.NewAddContributionLogic(ctx, s.svcCtx)
	return l.AddContribution(in)
}

func (s *ContributionServer) DelAllContributionInCategoryByDeveloperId(ctx context.Context, in *contribution.DelAllContributionInCategoryByDeveloperIdReq) (*contribution.DelAllContributionInCategoryByDeveloperIdResp, error) {
	l := logic.NewDelAllContributionInCategoryByDeveloperIdLogic(ctx, s.svcCtx)
	return l.DelAllContributionInCategoryByDeveloperId(in)
}

func (s *ContributionServer) SearchByCategory(ctx context.Context, in *contribution.SearchByCategoryReq) (*contribution.SearchByCategoryResp, error) {
	l := logic.NewSearchByCategoryLogic(ctx, s.svcCtx)
	return l.SearchByCategory(in)
}

func (s *ContributionServer) SearchByDeveloperId(ctx context.Context, in *contribution.SearchByDeveloperIdReq) (*contribution.SearchByDeveloperIdResp, error) {
	l := logic.NewSearchByDeveloperIdLogic(ctx, s.svcCtx)
	return l.SearchByDeveloperId(in)
}

func (s *ContributionServer) SearchByRepoId(ctx context.Context, in *contribution.SearchByRepoIdReq) (*contribution.SearchByRepoIdResp, error) {
	l := logic.NewSearchByRepoIdLogic(ctx, s.svcCtx)
	return l.SearchByRepoId(in)
}
