// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	api "github.com/wushiling50/aster/cmd/api/biz/model/api"
	"github.com/wushiling50/aster/cmd/api/biz/pack"
)

// TalentRank .
// @router /aster/talent/rank/ [GET]
func TalentRank(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.TalentRankRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.TalentRankResponse)

	// TODO: invoke service

	pack.SendResponse(c, resp)
}

// Search .
// @router /aster/search [GET]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.SearchResponse)

	// TODO: invoke service

	pack.SendResponse(c, resp)
}
