// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/wushiling50/aster/cmd/api/biz/model/api"
)

// TalentRank .
// @router /aster/talent/rank/ [GET]
func TalentRank(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.TalentRankRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.TalentRankResponse)

	c.JSON(consts.StatusOK, resp)
}

// NationGuess .
// @router /aster/nation/guess [GET]
func NationGuess(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.NationGuessRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.NationGuessResponse)

	c.JSON(consts.StatusOK, resp)
}

// Search .
// @router /aster/search [GET]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.SearchResponse)

	c.JSON(consts.StatusOK, resp)
}
