// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	api "github.com/wushiling50/aster/cmd/api/biz/model/api"
	"github.com/wushiling50/aster/cmd/api/biz/pack"
	"github.com/wushiling50/aster/cmd/base/service"
)

// TalentRank .
// @router /aster/talent/rank/ [GET]
func TalentRank(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.TalentRankRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.TalentRankResponse)

	s := service.NewBaseService(ctx)
	userInfo, err := s.TalentRank(ctx, &req)
	if err != nil {
		hlog.Error(err)
		pack.SendFailResponse(c, err)
		return
	}
	resp.UserInfo = userInfo

	pack.SendResponse(c, resp)
}

// Search .
// @router /aster/search [GET]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.SearchResponse)

	s := service.NewBaseService(ctx)
	userList, err := s.Search(ctx, &req)
	if err != nil {
		hlog.Error(err)
		pack.SendFailResponse(c, err)
		return
	}

	resp.UserList = userList

	pack.SendResponse(c, resp)
}
